In [1]:
print('Hello World')

Hello World

In [ ]:
import pandas as pd

# This will format the float numbers to display only two decimal places.
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [ ]:
# This will show the version of pandas installed in your environment.
pd.__version__

'3.0.3'

In [ ]:
# Populating a DataFrame with sample data for demonstration purposes.
data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04"],
    "close": [150.0, 152.0, 153.0, 154.0],
    "volume": [1000, 1200, 1300, 1250],
}

df = pd.DataFrame(data)

print(df)

df

         date    close  volume
0  2022-01-01 150.0000    1000
1  2022-01-02 152.0000    1200
2  2022-01-03 153.0000    1300
3  2022-01-04 154.0000    1250

         date    close  volume
0  2022-01-01 150.0000    1000
1  2022-01-02 152.0000    1200
2  2022-01-03 153.0000    1300
3  2022-01-04 154.0000    1250

In [ ]:
# This will show the index of the DataFrame.
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# This will convert the index to a list and display it.
print(list(df.index))

[0, 1, 2, 3]

In [ ]:
# This will display the 'date' column of the DataFrame.
print(df['date'])

0    2022-01-01
1    2022-01-02
2    2022-01-03
3    2022-01-04
Name: date, dtype: str

In [ ]:
# This will display the 'close' column of the DataFrame.
print(df['close'])

0   150.0000
1   152.0000
2   153.0000
3   154.0000
Name: close, dtype: float64

In [ ]:
# This will display the row at index 2 of the DataFrame.
print(df.loc[2])

date      2022-01-03
close       153.0000
volume          1300
Name: 2, dtype: object

In [ ]:
# This will display the 'volume' value of the row at index 2 using iloc.
print(df.iloc[2]['volume'])

1300

In [ ]:
# This will display the 'volume' value of the row at index 2 using iloc.
print(df['volume'].iloc[2])

1300

In [ ]:
# This will display the 'volume' and 'close' values of the row at index 2 using iloc.
print(df[['volume','close']].iloc[2])

volume   1300.0000
close     153.0000
Name: 2, dtype: float64

In [ ]:
# This will display the 'volume' and 'close' columns of the DataFrame.
print(df[['volume','close']])

   volume    close
0    1000 150.0000
1    1200 152.0000
2    1300 153.0000
3    1250 154.0000

In [ ]:
# This will return a boolean Series indicating which rows have 'volume' greater than 1300.
df['volume'] > 1300

0    False
1    False
2    False
3    False
Name: volume, dtype: bool

In [ ]:
# This will return a boolean Series indicating which rows have 'volume' greater than or equal to 1250.
df['volume'] >= 1250

0    False
1    False
2     True
3     True
Name: volume, dtype: bool

In [ ]:
# This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250.
df.loc[df['volume'] >= 1250]

         date    close  volume
2  2022-01-03 153.0000    1300
3  2022-01-04 154.0000    1250

In [ ]:
# This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250 and 'close' is greater than 153. 
df.loc[(df['volume'] >= 1250) & (df['close'] > 153)]

         date    close  volume
3  2022-01-04 154.0000    1250

In [ ]:
# This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250 or 'close' is greater than 153.
df.loc[(df['volume'] >= 1250) | (df['close'] > 153)]

         date    close  volume
2  2022-01-03 153.0000    1300
3  2022-01-04 154.0000    1250

In [19]:
# This will return the 'volume' values of the rows where 'volume' is greater than or equal to 1250 or 'close' is greater than 153.
df['volume'].loc[(df['volume'] >= 1250) | (df['close'] > 153)]

2    1300
3    1250
Name: volume, dtype: int64

In [ ]:
# This will read the CSV file 'APPL_1D.csv' into a DataFrame.
df = pd.read_csv('APPL_1D.csv')

In [21]:
df

,time,open,high,low,close,volume,Volume MA
0,1320240600,12.1448,12.1554,11.9936,12.0634,328255052.0000,565663058.2000
1,1320327000,12.1138,12.2452,12.0012,12.2352,441524796.0000,547110249.4000
2,1320413400,12.2036,12.2464,12.1165,12.1493,302228240.0000,535440799.6000
3,1320676200,12.1393,12.1420,12.0246,12.1338,270274636.0000,526828854.8000
4,1320762600,12.2091,12.3849,12.1894,12.3311,400439768.0000,516566707.4000
...,...,...,...,...,...,...,...
2915,1686058200,179.9650,180.1200,177.4300,179.2100,64848374.0000,58818603.7500
2916,1686144600,178.4400,181.2100,177.3200,177.8200,61944615.0000,59649490.8000
2917,1686231000,177.8950,180.8400,177.4600,180.5700,50214881.0000,59474009.8000
2918,1686317400,181.5000,182.2300,180.6300,180.9600,48899973.0000,59443274.6500
2919,1686576600,181.2700,NaN,NaN,NaN,NaN,NaN

In [ ]:
# This will provide a statistical summary of the DataFrame's numerical columns.
df.describe()

,time,open,high,low,close,volume,Volume MA
count,2920.0000,2920.0000,2919.0000,2919.0000,2919.0000,2919.0000,2919.0000
mean,1503502927.3973,59.7426,60.3816,59.0700,59.7542,200558014.5115,202115717.4892
std,105701072.4096,51.3041,51.9049,50.6559,51.3130,171035615.1915,148989947.0812
min,1320240600.0000,0.0000,11.2663,11.0286,11.0362,35195860.0000,50684940.6500
25%,1412062200.0000,21.8347,22.0909,21.6194,21.8520,91766241.0000,101733696.1000
50%,1503451800.0000,36.4903,36.7245,36.1785,36.5761,137148384.0000,138776456.2000
75%,1595057400.0000,93.8277,94.5549,92.2734,93.8406,247976166.0000,250714603.0000
max,1686576600.0000,182.6300,184.9510,180.6300,180.9600,1506113440.0000,807241634.0000

In [ ]:
# This will drop the 'Volume MA' column from the DataFrame if it exists, and ignore any errors if it doesn't.
df = df.drop('Volume MA', axis=1, errors='ignore') 
df

            time     open     high      low    close         volume
0     1320240600  12.1448  12.1554  11.9936  12.0634 328255052.0000
1     1320327000  12.1138  12.2452  12.0012  12.2352 441524796.0000
2     1320413400  12.2036  12.2464  12.1165  12.1493 302228240.0000
3     1320676200  12.1393  12.1420  12.0246  12.1338 270274636.0000
4     1320762600  12.2091  12.3849  12.1894  12.3311 400439768.0000
...          ...      ...      ...      ...      ...            ...
2915  1686058200 179.9650 180.1200 177.4300 179.2100  64848374.0000
2916  1686144600 178.4400 181.2100 177.3200 177.8200  61944615.0000
2917  1686231000 177.8950 180.8400 177.4600 180.5700  50214881.0000
2918  1686317400 181.5000 182.2300 180.6300 180.9600  48899973.0000
2919  1686576600 181.2700      NaN      NaN      NaN            NaN

[2920 rows x 6 columns]

In [ ]:
# This will return a DataFrame of the same shape as df, with boolean values indicating whether each element is null (True) or not (False).
df.isnull()

       time   open   high    low  close  volume
0     False  False  False  False  False   False
1     False  False  False  False  False   False
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
2915  False  False  False  False  False   False
2916  False  False  False  False  False   False
2917  False  False  False  False  False   False
2918  False  False  False  False  False   False
2919  False  False   True   True   True    True

[2920 rows x 6 columns]

In [ ]:
# This will return a boolean Series indicating which rows in the 'high' column are null (True) or not (False).
df['high'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919     True
Name: high, Length: 2920, dtype: bool

In [ ]:
# This will return the rows of the DataFrame where the 'high' column is null.
df.loc[df['high'].isnull()]

            time     open  high  low  close  volume
2919  1686576600 181.2700   NaN  NaN    NaN     NaN

In [ ]:
# This will drop the row with index 2919 from the DataFrame.
df = df.drop(2919) 
df

            time     open     high      low    close         volume
0     1320240600  12.1448  12.1554  11.9936  12.0634 328255052.0000
1     1320327000  12.1138  12.2452  12.0012  12.2352 441524796.0000
2     1320413400  12.2036  12.2464  12.1165  12.1493 302228240.0000
3     1320676200  12.1393  12.1420  12.0246  12.1338 270274636.0000
4     1320762600  12.2091  12.3849  12.1894  12.3311 400439768.0000
...          ...      ...      ...      ...      ...            ...
2914  1685971800 182.6300 184.9510 178.0350 179.5800 121946497.0000
2915  1686058200 179.9650 180.1200 177.4300 179.2100  64848374.0000
2916  1686144600 178.4400 181.2100 177.3200 177.8200  61944615.0000
2917  1686231000 177.8950 180.8400 177.4600 180.5700  50214881.0000
2918  1686317400 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 6 columns]

In [28]:
# This will provide a statistical summary of the DataFrame's numerical columns 
df.describe()

                 time      open      high       low     close          volume
count       2919.0000 2919.0000 2919.0000 2919.0000 2919.0000       2919.0000
mean  1503440209.4553   59.7010   60.3816   59.0700   59.7542  200558014.5115
std    105664827.3087   51.2636   51.9049   50.6559   51.3130  171035615.1915
min   1320240600.0000    0.0000   11.2663   11.0286   11.0362   35195860.0000
25%   1412040600.0000   21.8318   22.0909   21.6194   21.8520   91766241.0000
50%   1503408600.0000   36.4703   36.7245   36.1785   36.5761  137148384.0000
75%   1594949400.0000   93.3571   94.5549   92.2734   93.8406  247976166.0000
max   1686317400.0000  182.6300  184.9510  180.6300  180.9600 1506113440.0000

In [ ]:
# Converting the 'time' column to datetime format from integer seconds since epoch.
df["time"] = pd.to_datetime(df["time"].astype("int64"), unit="s")
print(df["time"])

0      2011-11-02 13:30:00
1      2011-11-03 13:30:00
2      2011-11-04 13:30:00
3      2011-11-07 14:30:00
4      2011-11-08 14:30:00
               ...
2914   2023-06-05 13:30:00
2915   2023-06-06 13:30:00
2916   2023-06-07 13:30:00
2917   2023-06-08 13:30:00
2918   2023-06-09 13:30:00
Name: time, Length: 2919, dtype: datetime64[s]

In [30]:
df['open'] == 0

0       False
1       False
2       False
3       False
4       False
        ...
2914    False
2915    False
2916    False
2917    False
2918    False
Name: open, Length: 2919, dtype: bool

In [ ]:
# This will return the rows of the DataFrame where the 'open' column is equal to 0.
df.loc[df['open'] == 0] 
df

                    time     open     high      low    close         volume
0    2011-11-02 13:30:00  12.1448  12.1554  11.9936  12.0634 328255052.0000
1    2011-11-03 13:30:00  12.1138  12.2452  12.0012  12.2352 441524796.0000
2    2011-11-04 13:30:00  12.2036  12.2464  12.1165  12.1493 302228240.0000
3    2011-11-07 14:30:00  12.1393  12.1420  12.0246  12.1338 270274636.0000
4    2011-11-08 14:30:00  12.2091  12.3849  12.1894  12.3311 400439768.0000
...                  ...      ...      ...      ...      ...            ...
2914 2023-06-05 13:30:00 182.6300 184.9510 178.0350 179.5800 121946497.0000
2915 2023-06-06 13:30:00 179.9650 180.1200 177.4300 179.2100  64848374.0000
2916 2023-06-07 13:30:00 178.4400 181.2100 177.3200 177.8200  61944615.0000
2917 2023-06-08 13:30:00 177.8950 180.8400 177.4600 180.5700  50214881.0000
2918 2023-06-09 13:30:00 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 6 columns]

In [ ]:
# Setting up a time column in dataframe as an index column
# This will set the 'time' column as the index of the DataFrame, modifying it in place.
df.set_index('time', inplace=True) 
df

                        open     high      low    close         volume
time
2011-11-02 13:30:00  12.1448  12.1554  11.9936  12.0634 328255052.0000
2011-11-03 13:30:00  12.1138  12.2452  12.0012  12.2352 441524796.0000
2011-11-04 13:30:00  12.2036  12.2464  12.1165  12.1493 302228240.0000
2011-11-07 14:30:00  12.1393  12.1420  12.0246  12.1338 270274636.0000
2011-11-08 14:30:00  12.2091  12.3849  12.1894  12.3311 400439768.0000
...                      ...      ...      ...      ...            ...
2023-06-05 13:30:00 182.6300 184.9510 178.0350 179.5800 121946497.0000
2023-06-06 13:30:00 179.9650 180.1200 177.4300 179.2100  64848374.0000
2023-06-07 13:30:00 178.4400 181.2100 177.3200 177.8200  61944615.0000
2023-06-08 13:30:00 177.8950 180.8400 177.4600 180.5700  50214881.0000
2023-06-09 13:30:00 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 5 columns]

In [33]:
df

                        open     high      low    close         volume
time
2011-11-02 13:30:00  12.1448  12.1554  11.9936  12.0634 328255052.0000
2011-11-03 13:30:00  12.1138  12.2452  12.0012  12.2352 441524796.0000
2011-11-04 13:30:00  12.2036  12.2464  12.1165  12.1493 302228240.0000
2011-11-07 14:30:00  12.1393  12.1420  12.0246  12.1338 270274636.0000
2011-11-08 14:30:00  12.2091  12.3849  12.1894  12.3311 400439768.0000
...                      ...      ...      ...      ...            ...
2023-06-05 13:30:00 182.6300 184.9510 178.0350 179.5800 121946497.0000
2023-06-06 13:30:00 179.9650 180.1200 177.4300 179.2100  64848374.0000
2023-06-07 13:30:00 178.4400 181.2100 177.3200 177.8200  61944615.0000
2023-06-08 13:30:00 177.8950 180.8400 177.4600 180.5700  50214881.0000
2023-06-09 13:30:00 181.5000 182.2300 180.6300 180.9600  48899973.0000

[2919 rows x 5 columns]

In [ ]:
# This will return the row of the DataFrame corresponding to the date '2023-03-13'.
df.loc['2023-03-13']

                        open     high      low    close        volume
time
2023-03-13 13:30:00 147.6008 152.9285 147.4960 150.2622 84457122.0000

In [ ]:
# This will return all the rows of the DataFrame corresponding to the year 2023.
df.loc['2023']

                        open     high      low    close         volume
time
2023-01-03 14:30:00 129.9017 130.5199 123.8094 124.7068 112117471.0000
2023-01-04 14:30:00 126.5216 128.2821 124.7168 125.9931  89113633.0000
2023-01-05 14:30:00 126.7609 127.3990 124.3977 124.6570  80962708.0000
2023-01-06 14:30:00 125.6441 129.9117 124.5274 129.2436  87754715.0000
2023-01-09 14:30:00 130.0862 133.0226 129.5128 129.7721  70790813.0000
...                      ...      ...      ...      ...            ...
2023-06-05 13:30:00 182.6300 184.9510 178.0350 179.5800 121946497.0000
2023-06-06 13:30:00 179.9650 180.1200 177.4300 179.2100  64848374.0000
2023-06-07 13:30:00 178.4400 181.2100 177.3200 177.8200  61944615.0000
2023-06-08 13:30:00 177.8950 180.8400 177.4600 180.5700  50214881.0000
2023-06-09 13:30:00 181.5000 182.2300 180.6300 180.9600  48899973.0000

[110 rows x 5 columns]

In [ ]:
# This will return all the rows of the DataFrame corresponding to the years 2021 and 2022.
df.loc['2021' : '2022']

                        open     high      low    close         volume
time
2021-01-04 14:30:00 131.5531 131.6433 124.8927 127.5036 143301887.0000
2021-01-05 14:30:00 126.9913 129.7993 126.5381 129.0801  97664898.0000
2021-01-06 14:30:00 125.8385 129.1194 124.5202 124.7350 155087970.0000
2021-01-07 14:30:00 126.4691 129.6909 125.9765 128.9914 109578157.0000
2021-01-08 14:30:00 130.4792 130.6762 128.3116 130.1047 105158245.0000
...                      ...      ...      ...      ...            ...
2022-12-23 14:30:00 130.5399 132.0305 129.2636 131.4771  63814893.0000
2022-12-27 14:30:00 130.9985 131.0284 128.3462 129.6524  69007830.0000
2022-12-28 14:30:00 129.2935 130.6470 125.5045 125.6740  85438391.0000
2022-12-29 14:30:00 127.6184 130.1025 127.3591 129.2337  75703710.0000
2022-12-30 14:30:00 128.0371 129.5727 127.0600 129.5527  77034209.0000

[503 rows x 5 columns]

In [ ]:
# this doesn't work because the index is now a datetime index, and there is no row with index 3. 
# You can use df.iloc[3] to access the fourth row by its integer position.
df.loc[3]

KeyError: 3

In [ ]:
# This will return the fourth row of the DataFrame using its integer position.
df.iloc[3]

open      1.213929e+01
high      1.214203e+01
low       1.202455e+01
close     1.213383e+01
volume    2.702746e+08
Name: 2011-11-07 14:30:00, dtype: float64

In [ ]:
# This will create a new column 'low_high_avg' in the DataFrame, which is the average of the 'low' and 'high' columns.
df['low_high_avg'] = (df['low'] + df['high'] / 2)
df

,open,high,low,close,volume,low_high_avg
time,,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0,18.071286
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0,18.123800
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0,18.239751
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0,18.095565
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0,18.381818
...,...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0,270.510500
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0,267.490000
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0,267.925000
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0,267.880000
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0,271.745000

In [ ]:
# This will return the rows of the DataFrame where the 'open' column is equal to 0.
df.loc[df['open'] == 0]

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,0.0,25.306911,24.784321,25.172889,208258972.0,37.437776

In [ ]:
# This will set the 'open' value to the average of 'low' and 'high' for rows where 'open' is equal to 0.
df.loc[df['open'] == 0, 'open'] = df['low_high_avg']

In [ ]:
# Checking if there are any rows where 'open' is still equal to 0 after the update.
df.loc[df['open'] == 0]

Empty DataFrame
Columns: [open, high, low, close, volume, low_high_avg]
Index: []

In [ ]:
# This will return the row of the DataFrame corresponding to the date '2015-10-05'.
df.loc['2015-10-05']

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,37.437776,25.306911,24.784321,25.172889,208258972.0,37.437776

In [ ]:
# Checking the statistical summary of the DataFrame after the updates.
df.describe()

,open,high,low,close,volume,low_high_avg
count,2919.000000,2919.000000,2919.000000,2919.000000,2.919000e+03,2919.000000
mean,59.713811,60.381601,59.070005,59.754203,2.005580e+08,89.260805
std,51.253308,51.904884,50.655862,51.312979,1.710356e+08,76.605531
min,11.183412,11.266281,11.028606,11.036195,3.519586e+07,16.661747
25%,21.840326,22.090857,21.619382,21.852009,9.176624e+07,32.653514
50%,36.510268,36.724498,36.178549,36.576141,1.371484e+08,54.620716
75%,93.357071,94.554869,92.273407,93.840608,2.479762e+08,139.622636
max,182.630000,184.951000,180.630000,180.960000,1.506113e+09,271.745000

In [ ]:
# Calculating the mean, median, and standard deviation of the 'close' column in the DataFrame.
mean_prices = df["close"].mean()
median_prices = df["close"].median()
std_prices = df["close"].std()

# Printing the calculated statistics for the 'close' column.
print("Average closing prices:", round(mean_prices,2), '$')
print("Median closing prices:", median_prices)
print("Standard deviation of closing prices:", std_prices)

Average closing prices: 59.75 $
Median closing prices: 36.57614127
Standard deviation of closing prices: 51.312979089193696

In [ ]:
# Creating a moving average of the closing prices with a window of 9 days
df['close_ma'] = df['close'].rolling(window=9).mean()
df

,open,high,low,close,volume,low_high_avg,close_ma
time,,,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0,18.071286,NaN
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0,18.123800,NaN
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0,18.239751,NaN
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0,18.095565,NaN
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0,18.381818,NaN
...,...,...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0,270.510500,176.332222
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0,267.490000,177.182222
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0,267.925000,177.846667
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0,267.880000,178.688889
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0,271.745000,179.303333

In [ ]:
# Checking the statistical summary of the DataFrame after adding the moving average column.
df.describe()

,open,high,low,close,volume,low_high_avg,close_ma
count,2919.000000,2919.000000,2919.000000,2919.000000,2.919000e+03,2919.000000,2911.000000
mean,59.713811,60.381601,59.070005,59.754203,2.005580e+08,89.260805,59.654694
std,51.253308,51.904884,50.655862,51.312979,1.710356e+08,76.605531,51.129528
min,11.183412,11.266281,11.028606,11.036195,3.519586e+07,16.661747,11.332391
25%,21.840326,22.090857,21.619382,21.852009,9.176624e+07,32.653514,21.949145
50%,36.510268,36.724498,36.178549,36.576141,1.371484e+08,54.620716,36.526475
75%,93.357071,94.554869,92.273407,93.840608,2.479762e+08,139.622636,93.781973
max,182.630000,184.951000,180.630000,180.960000,1.506113e+09,271.745000,179.303333

In [ ]:
# Creating a new column 'daily_return' that calculates the daily return of the stock based on the 'close' price.

df['daily_return'] = df['close'].pct_change()  # This will calculate the daily return as the percentage change in the 'close' price from the previous day.
df['volatility'] = df['daily_return'].rolling(30).std()  # This will calculate the rolling standard deviation of the 'daily_return' over a window of 30 days, which is a measure of volatility.
df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility
time,,,,,,,,,
2011-11-02 13:30:00,12.1448,12.1554,11.9936,12.0634,328255052.0000,18.0713,NaN,NaN,NaN
2011-11-03 13:30:00,12.1138,12.2452,12.0012,12.2352,441524796.0000,18.1238,NaN,0.0142,NaN
2011-11-04 13:30:00,12.2036,12.2464,12.1165,12.1493,302228240.0000,18.2398,NaN,-0.0070,NaN
2011-11-07 14:30:00,12.1393,12.1420,12.0246,12.1338,270274636.0000,18.0956,NaN,-0.0013,NaN
2011-11-08 14:30:00,12.2091,12.3849,12.1894,12.3311,400439768.0000,18.3818,NaN,0.0163,NaN
...,...,...,...,...,...,...,...,...,...
2023-06-05 13:30:00,182.6300,184.9510,178.0350,179.5800,121946497.0000,270.5105,176.3322,-0.0076,0.0124
2023-06-06 13:30:00,179.9650,180.1200,177.4300,179.2100,64848374.0000,267.4900,177.1822,-0.0021,0.0125
2023-06-07 13:30:00,178.4400,181.2100,177.3200,177.8200,61944615.0000,267.9250,177.8467,-0.0078,0.0124
2023-06-08 13:30:00,177.8950,180.8400,177.4600,180.5700,50214881.0000,267.8800,178.6889,0.0155,0.0126
2023-06-09 13:30:00,181.5000,182.2300,180.6300,180.9600,48899973.0000,271.7450,179.3033,0.0022,0.0117

In [ ]:
# Sorting the DataFrame by a column colatility in descending order to see the most volatile days at the top.

df.sort_values(by='daily_return', ascending=True, inplace=True) # This will sort the DataFrame by the 'daily_return' column in ascending order, modifying it in place.

df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility
time,,,,,,,,,
2020-03-16 13:30:00,59.2264,63.4196,58.7491,59.2901,322423460.0000,90.4589,67.4537,-0.1286,0.0513
2013-01-24 14:30:00,14.0873,14.2628,13.7887,13.7964,1460853300.0000,20.9201,15.2647,-0.1235,0.0307
2019-01-03 14:30:00,34.6406,35.0593,34.1642,34.2100,365248780.0000,51.6939,36.9388,-0.0996,0.0312
2020-03-12 13:30:00,62.6510,66.0927,60.7074,60.7637,418474068.0000,93.7537,69.3019,-0.0988,0.0402
2020-09-03 13:30:00,124.8251,126.7234,118.5204,118.8942,257599640.0000,181.8821,124.8615,-0.0801,0.0311
...,...,...,...,...,...,...,...,...,...
2020-03-02 14:30:00,69.0987,73.7888,67.9825,73.1450,341397356.0000,104.8769,72.9351,0.0931,0.0289
2020-03-24 13:30:00,57.8580,60.6315,57.3538,60.4332,287531092.0000,87.6695,60.1963,0.1003,0.0562
2020-07-31 13:30:00,101.0114,104.4784,98.9902,104.3263,374295468.0000,151.2294,94.3931,0.1047,0.0254
2020-03-13 13:30:00,64.8418,68.5210,61.9191,68.0437,370732128.0000,96.1796,68.7351,0.1198,0.0464
2011-11-02 13:30:00,12.1448,12.1554,11.9936,12.0634,328255052.0000,18.0713,NaN,NaN,NaN

In [ ]:
# Calculating the change between the 'close' and 'open' prices as a percentage of the 'close' price and storing it in a new column 'change'.
df['change'] = (df['close'] - df['open']) / df['close'] 
# This will sort the DataFrame by the 'change' column in ascending order, modifying it in place.
df.sort_values(by='change', ascending=True, inplace=True) 
df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility,change
time,,,,,,,,,,
2015-10-05 13:30:00,37.4378,25.3069,24.7843,25.1729,208258972.0000,37.4378,25.4140,0.0036,0.0217,-0.4872
2020-03-20 13:30:00,60.5066,61.6449,55.8116,56.1152,401693384.0000,86.6341,62.6311,-0.0635,0.0525,-0.0783
2015-08-25 13:30:00,25.2479,25.2479,23.5186,23.5732,414406396.0000,36.1426,25.3756,0.0060,0.0211,-0.0710
2020-09-10 13:30:00,118.3827,118.5204,110.6518,111.6256,182274391.0000,169.9121,120.7496,-0.0326,0.0349,-0.0605
2012-12-05 14:30:00,17.4227,17.4331,16.4996,16.5003,1044638484.0000,25.2162,17.7086,-0.0643,0.0256,-0.0559
...,...,...,...,...,...,...,...,...,...,...
2022-10-13 13:30:00,134.3751,142.9360,133.7579,142.3387,113223975.0000,205.2259,141.7071,0.0336,0.0230,0.0559
2018-12-26 14:30:00,35.6800,37.8285,35.2998,37.8140,234330176.0000,54.2141,38.4653,0.0704,0.0282,0.0564
2020-02-28 14:30:00,62.9741,68.1514,62.7562,66.9152,426884920.0000,96.8319,73.4842,-0.0006,0.0229,0.0589
2022-02-24 14:30:00,151.4518,161.6459,150.8761,161.5367,141147540.0000,231.6990,166.1148,0.0167,0.0196,0.0624
2015-08-24 13:30:00,21.5576,24.7230,20.9055,23.4323,648825168.0000,33.2669,25.6660,-0.0250,0.0210,0.0800

In [ ]:
# Importing CVS into new df with pandas
df_t = pd.read_csv('TITANIC.csv')  # This will read the CSV file 'TITANIC.csv' into a new DataFrame df_t.

df_t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0000,0,0,370376,7.7500,NaN,Q

In [ ]:
# Looking at the first 10 rows of the Titanic DataFrame to get an overview of the data.
df_t.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0000,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0000,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0000,1,0,237736,30.0708,NaN,C

In [ ]:
# Determine the dataset's dimensions (i.e. the number of rows and columns).

df_t.shape  # This will return a tuple representing the dimensions of the DataFrame, where the first element is the number of rows and the second element is the number of columns.

(891, 12)

In [ ]:
# Count the number of passengers in each class (Pclass).

df_t['Pclass'].value_counts()  # This will return a Series containing counts of unique values in the 'Pclass' column, effectively counting the number of passengers in each class.

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
# This will calculate the average age of passengers in the Titanic dataset.
average_age = df_t['Age'].mean()  
average_age

np.float64(29.69911764705882)

In [ ]:
# Sorting the Titanic DataFrame by the 'Age' column in descending order to find the oldest passengers.
df_t.sort_values(by='Age', ascending=False, inplace=True)
df_t

#Oldest - Barkworth, Mr. Algernon Henry Wilson

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0000,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0000,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5000,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
# Sorting the Titanic DataFrame by the 'Age' column in ascending order to find the youngest passengers.
df_t.sort_values(by='Age', ascending=True, inplace=True)
df_t

# Youngest - Thomas, Master. Assad Alexander

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.4200,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.6700,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.7500,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.7500,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.8300,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
# Counting the number of survivors and non-survivors in the Titanic dataset.
df_t['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
# Counting the number of male and female passengers in the Titanic dataset.
df_t['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# Calculate How many men survived
men_survived = df_t[(df_t['Sex'] == 'male') & (df_t['Survived'] == 1)].shape[0]  # This will count the number of male passengers who survived.
men_survived

109

In [ ]:
# Calculate How many women survived
women_survived = df_t[(df_t['Sex'] == 'female') & (df_t['Survived'] == 1)].shape[0]
women_survived

233

In [ ]:
# Other way to calculate how many women survived using len() function instead of shape[0].
women_survived1 = len(df_t[(df_t['Sex'] == 'female') & (df_t['Survived'] == 1)])
women_survived1

233

In [ ]:
# Calculate the survival rate for each passenger class (Pclass) in the Titanic dataset.
first_class_survival_rate = df_t[df_t['Pclass'] == 1]['Survived'].mean()  
print(first_class_survival_rate)

second_class_survival_rate = df_t[df_t['Pclass'] == 2]['Survived'].mean()
print(second_class_survival_rate)

third_class_survival_rate = df_t[df_t['Pclass'] == 3]['Survived'].mean()
print(third_class_survival_rate)

0.6296296296296297
0.47282608695652173
0.24236252545824846

In [ ]:
# Calculating the total number of passengers in first class and the number of survivors in first class to compute the survival rate.
first_class_total = len(df_t['Pclass'] == 1)
print(first_class_total)

first_class_survived = len(df_t[(df_t['Pclass'] == 1) & (df_t['Survived'] == 1)])
print(first_class_survived)

first_class_survival_rate2 = first_class_survived / first_class_total
print(first_class_survival_rate2)

891
136
0.1526374859708193

In [ ]:
# Selecting the 'Survived' column for passengers in first class to analyze their survival status.
first_class_survival_rate = df_t[df_t['Pclass'] == 1]['Survived']
first_class_survival_rate

305    1
297    0
445    1
802    1
435    1
      ..
766    0
793    0
815    0
839    1
849    1
Name: Survived, Length: 216, dtype: int64

In [ ]:
# Creating a new column 'FamilySize' in the Titanic DataFrame that represents the total number of family members aboard (siblings/spouses + parents/children).
df_t['FamilySize'] = df_t['SibSp'] + df_t['Parch']
df_t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.4200,0,1,2625,8.5167,NaN,C,1
755,756,1,2,"Hamalainen, Master. Viljo",male,0.6700,1,1,250649,14.5000,NaN,S,2
644,645,1,3,"Baclini, Miss. Eugenie",female,0.7500,2,1,2666,19.2583,NaN,C,3
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.7500,2,1,2666,19.2583,NaN,C,3
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.8300,0,2,248738,29.0000,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,0
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3

In [ ]:
# Sorting the Titanic DataFrame by the 'FamilySize' column in descending order to find passengers
# who did not survive and had the largest families aboard.
df_t[df_t['Survived'] == 0].sort_values(by='FamilySize', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,266,0,2,"Reeves, Mr. David",male,36.0000,0,0,C.A. 17248,10.5000,NaN,S,0
292,293,0,2,"Levy, Mr. Rene Jacques",male,36.0000,0,0,SC/Paris 2163,12.8750,D,C,0
614,615,0,3,"Brocklebank, Mr. William Alfred",male,35.0000,0,0,364512,8.0500,NaN,S,0
812,813,0,2,"Slemen, Mr. Richard James",male,35.0000,0,0,28206,10.5000,NaN,S,0
800,801,0,2,"Ponesell, Mr. Martin",male,34.0000,0,0,250647,13.0000,NaN,S,0

In [ ]:
# Clean alternative using .query()
df_t.query('Survived == 0').sort_values(by='FamilySize', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,266,0,2,"Reeves, Mr. David",male,36.0000,0,0,C.A. 17248,10.5000,NaN,S,0
292,293,0,2,"Levy, Mr. Rene Jacques",male,36.0000,0,0,SC/Paris 2163,12.8750,D,C,0
614,615,0,3,"Brocklebank, Mr. William Alfred",male,35.0000,0,0,364512,8.0500,NaN,S,0
812,813,0,2,"Slemen, Mr. Richard James",male,35.0000,0,0,28206,10.5000,NaN,S,0
800,801,0,2,"Ponesell, Mr. Martin",male,34.0000,0,0,250647,13.0000,NaN,S,0