In [1]:
print('Hello World')

Hello World

In [132]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.4f' % x)  # This will format the float numbers to display only two decimal places.

In [4]:
pd.__version__ # This will show the version of pandas installed in your environment.

'3.0.3'

In [7]:
data = {
    "date": ["2022-01-01", "2022-01-02", "2022-01-03", "2022-01-04"],
    "close": [150.0, 152.0, 153.0, 154.0],
    "volume": [1000, 1200, 1300, 1250],
}

df = pd.DataFrame(data)

print(df)

df

         date  close  volume
0  2022-01-01  150.0    1000
1  2022-01-02  152.0    1200
2  2022-01-03  153.0    1300
3  2022-01-04  154.0    1250

         date  close  volume
0  2022-01-01  150.0    1000
1  2022-01-02  152.0    1200
2  2022-01-03  153.0    1300
3  2022-01-04  154.0    1250

In [8]:
print(df.index)  # This will show the index of the DataFrame.

RangeIndex(start=0, stop=4, step=1)

In [9]:
print(list(df.index))  # This will convert the index to a list and display it.

[0, 1, 2, 3]

In [10]:
print(df['date'])  # This will display the 'date' column of the DataFrame.

0    2022-01-01
1    2022-01-02
2    2022-01-03
3    2022-01-04
Name: date, dtype: str

In [11]:
print(df['close'])  # This will display the 'close' column of the DataFrame.

0    150.0
1    152.0
2    153.0
3    154.0
Name: close, dtype: float64

In [12]:
print(df.loc[2])  # This will display the row at index 2 of the DataFrame.

date      2022-01-03
close          153.0
volume          1300
Name: 2, dtype: object

In [15]:
print(df.iloc[2]['volume'])  # This will display the 'volume' value of the row at index 2 using iloc.

1300

In [18]:
print(df['volume'].iloc[2])  # This will display the 'volume' value of the row at index 2 using iloc.

1300

In [21]:
print(df[['volume','close']].iloc[2]) # This will display the 'volume' and 'close' values of the row at index 2 using iloc.

volume    1300.0
close      153.0
Name: 2, dtype: float64

In [23]:
print(df[['volume','close']]) # This will display the 'volume' and 'close' columns of the DataFrame.

   volume  close
0    1000  150.0
1    1200  152.0
2    1300  153.0
3    1250  154.0

In [24]:
df['volume'] > 1300 # This will return a boolean Series indicating which rows have 'volume' greater than 1300.

0    False
1    False
2    False
3    False
Name: volume, dtype: bool

In [25]:
df['volume'] >= 1250 # This will return a boolean Series indicating which rows have 'volume' greater than or equal to 1250.

0    False
1    False
2     True
3     True
Name: volume, dtype: bool

In [26]:
df.loc[df['volume'] >= 1250] # This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250.

         date  close  volume
2  2022-01-03  153.0    1300
3  2022-01-04  154.0    1250

In [30]:
df.loc[(df['volume'] >= 1250) & (df['close'] > 153)] 

# This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250 and 'close' is greater than 153.

         date  close  volume
3  2022-01-04  154.0    1250

In [32]:
df.loc[(df['volume'] >= 1250) | (df['close'] > 153)] 

# This will return the rows of the DataFrame where 'volume' is greater than or equal to 1250 or 'close' is greater than 153.

         date  close  volume
2  2022-01-03  153.0    1300
3  2022-01-04  154.0    1250

In [34]:
df['volume'].loc[(df['volume'] >= 1250) | (df['close'] > 153)] 

# This will return the 'volume' values of the rows where 'volume' is greater than or equal to 1250 or 'close' is greater than 153.

2    1300
3    1250
Name: volume, dtype: int64

In [35]:
df = pd.read_csv('APPL_1D.csv')  # This will read the CSV file 'APPL_1D.csv' into a DataFrame.

In [37]:
df

,time,open,high,low,close,volume,Volume MA
0,1320240600,12.144762,12.155382,11.993595,12.063406,328255052.0,5.656631e+08
1,1320327000,12.113800,12.245232,12.001184,12.235220,441524796.0,5.471102e+08
2,1320413400,12.203650,12.246448,12.116527,12.149313,302228240.0,5.354408e+08
3,1320676200,12.139294,12.142028,12.024551,12.133831,270274636.0,5.268289e+08
4,1320762600,12.209111,12.384869,12.189383,12.331139,400439768.0,5.165667e+08
...,...,...,...,...,...,...,...
2915,1686058200,179.965000,180.120000,177.430000,179.210000,64848374.0,5.881860e+07
2916,1686144600,178.440000,181.210000,177.320000,177.820000,61944615.0,5.964949e+07
2917,1686231000,177.895000,180.840000,177.460000,180.570000,50214881.0,5.947401e+07
2918,1686317400,181.500000,182.230000,180.630000,180.960000,48899973.0,5.944327e+07
2919,1686576600,181.270000,NaN,NaN,NaN,NaN,NaN

In [38]:
df.describe()  # This will provide a statistical summary of the DataFrame's numerical columns.

,time,open,high,low,close,volume,Volume MA
count,2.920000e+03,2920.000000,2919.000000,2919.000000,2919.000000,2.919000e+03,2.919000e+03
mean,1.503503e+09,59.742618,60.381601,59.070005,59.754203,2.005580e+08,2.021157e+08
std,1.057011e+08,51.304136,51.904884,50.655862,51.312979,1.710356e+08,1.489899e+08
min,1.320241e+09,0.000000,11.266281,11.028606,11.036195,3.519586e+07,5.068494e+07
25%,1.412062e+09,21.834683,22.090857,21.619382,21.852009,9.176624e+07,1.017337e+08
50%,1.503452e+09,36.490271,36.724498,36.178549,36.576141,1.371484e+08,1.387765e+08
75%,1.595057e+09,93.827722,94.554869,92.273407,93.840608,2.479762e+08,2.507146e+08
max,1.686577e+09,182.630000,184.951000,180.630000,180.960000,1.506113e+09,8.072416e+08

In [58]:
# Пришлось дописать errors='ignore' иначе будет ошибка, хотя столбец 'Volume MA' есть в DataFrame.
df = df.drop('Volume MA', axis=1, errors='ignore') # This will drop the 'Volume MA' column from the DataFrame if it exists, and ignore any errors if it doesn't.
df

            time        open        high         low       close       volume
0     1320240600   12.144762   12.155382   11.993595   12.063406  328255052.0
1     1320327000   12.113800   12.245232   12.001184   12.235220  441524796.0
2     1320413400   12.203650   12.246448   12.116527   12.149313  302228240.0
3     1320676200   12.139294   12.142028   12.024551   12.133831  270274636.0
4     1320762600   12.209111   12.384869   12.189383   12.331139  400439768.0
...          ...         ...         ...         ...         ...          ...
2915  1686058200  179.965000  180.120000  177.430000  179.210000   64848374.0
2916  1686144600  178.440000  181.210000  177.320000  177.820000   61944615.0
2917  1686231000  177.895000  180.840000  177.460000  180.570000   50214881.0
2918  1686317400  181.500000  182.230000  180.630000  180.960000   48899973.0
2919  1686576600  181.270000         NaN         NaN         NaN          NaN

[2920 rows x 6 columns]

In [60]:
df.isnull() # This will return a DataFrame of the same shape as df, with boolean values indicating whether each element is null (True) or not (False).

       time   open   high    low  close  volume
0     False  False  False  False  False   False
1     False  False  False  False  False   False
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
2915  False  False  False  False  False   False
2916  False  False  False  False  False   False
2917  False  False  False  False  False   False
2918  False  False  False  False  False   False
2919  False  False   True   True   True    True

[2920 rows x 6 columns]

In [61]:
df['high'].isnull() # This will return a boolean Series indicating which rows in the 'high' column are null (True) or not (False).

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919     True
Name: high, Length: 2920, dtype: bool

In [68]:
df.loc[df['high'].isnull()] # This will return the rows of the DataFrame where the 'high' column is null.

            time    open  high  low  close  volume
2919  1686576600  181.27   NaN  NaN    NaN     NaN

In [69]:
df = df.drop(2919) # This will drop the row with index 2919 from the DataFrame.
df

            time        open        high         low       close       volume
0     1320240600   12.144762   12.155382   11.993595   12.063406  328255052.0
1     1320327000   12.113800   12.245232   12.001184   12.235220  441524796.0
2     1320413400   12.203650   12.246448   12.116527   12.149313  302228240.0
3     1320676200   12.139294   12.142028   12.024551   12.133831  270274636.0
4     1320762600   12.209111   12.384869   12.189383   12.331139  400439768.0
...          ...         ...         ...         ...         ...          ...
2914  1685971800  182.630000  184.951000  178.035000  179.580000  121946497.0
2915  1686058200  179.965000  180.120000  177.430000  179.210000   64848374.0
2916  1686144600  178.440000  181.210000  177.320000  177.820000   61944615.0
2917  1686231000  177.895000  180.840000  177.460000  180.570000   50214881.0
2918  1686317400  181.500000  182.230000  180.630000  180.960000   48899973.0

[2919 rows x 6 columns]

In [93]:
df.describe()

              open         high          low        close        volume
count  2919.000000  2919.000000  2919.000000  2919.000000  2.919000e+03
mean     59.700985    60.381601    59.070005    59.754203  2.005580e+08
std      51.263568    51.904884    50.655862    51.312979  1.710356e+08
min       0.000000    11.266281    11.028606    11.036195  3.519586e+07
25%      21.831797    22.090857    21.619382    21.852009  9.176624e+07
50%      36.470273    36.724498    36.178549    36.576141  1.371484e+08
75%      93.357071    94.554869    92.273407    93.840608  2.479762e+08
max     182.630000   184.951000   180.630000   180.960000  1.506113e+09

In [94]:
df["time"] = pd.to_datetime(df["time"].astype("int64"), unit="s")
print(df["time"])

KeyError: 'time'

In [84]:
df['open'] == 0

0       False
1       False
2       False
3       False
4       False
        ...
2914    False
2915    False
2916    False
2917    False
2918    False
Name: open, Length: 2919, dtype: bool

In [96]:
df.loc[df['open'] == 0] # This will return the rows of the DataFrame where the 'open' column is equal to 0.
df

,open,high,low,close,volume
time,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0
...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0

In [99]:
# Setting up a time column in dataframe as an index column

df.set_index('time', inplace=True) # This will set the 'time' column as the index of the DataFrame, modifying it in place.
df

KeyError: "None of ['time'] are in the columns"

In [100]:
df

,open,high,low,close,volume
time,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0
...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0

In [103]:
df.loc['2023-03-13'] # This will return the row of the DataFrame corresponding to the date '2023-03-13'.

,open,high,low,close,volume
time,,,,,
2023-03-13 13:30:00,147.600838,152.928468,147.495983,150.262157,84457122.0

In [104]:
df.loc['2023']

,open,high,low,close,volume
time,,,,,
2023-01-03 14:30:00,129.901709,130.519908,123.809450,124.706837,112117471.0
2023-01-04 14:30:00,126.521552,128.282125,124.716808,125.993091,89113633.0
2023-01-05 14:30:00,126.760855,127.398997,124.397737,124.656982,80962708.0
2023-01-06 14:30:00,125.644107,129.911679,124.527359,129.243625,87754715.0
2023-01-09 14:30:00,130.086171,133.022620,129.512841,129.772086,70790813.0
...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0

In [105]:
df.loc['2021' : '2022']

,open,high,low,close,volume
time,,,,,
2021-01-04 14:30:00,131.553093,131.643344,124.892676,127.503638,143301887.0
2021-01-05 14:30:00,126.991299,129.799315,126.538075,129.080068,97664898.0
2021-01-06 14:30:00,125.838534,129.119381,124.520244,124.735033,155087970.0
2021-01-07 14:30:00,126.469106,129.690935,125.976472,128.991394,109578157.0
2021-01-08 14:30:00,130.479150,130.676204,128.311559,130.104748,105158245.0
...,...,...,...,...,...
2022-12-23 14:30:00,130.539850,132.030509,129.263567,131.477121,63814893.0
2022-12-27 14:30:00,130.998514,131.028427,128.346238,129.652434,69007830.0
2022-12-28 14:30:00,129.293480,130.647038,125.504514,125.674020,85438391.0
2022-12-29 14:30:00,127.618358,130.102524,127.359113,129.233654,75703710.0
2022-12-30 14:30:00,128.037138,129.572667,127.059984,129.552725,77034209.0

In [108]:
df.loc[3] # this doesn't work because the index is now a datetime index, and there is no row with index 3. You can use df.iloc[3] to access the fourth row by its integer position.

KeyError: 3

In [109]:
df.iloc[3]

open      1.213929e+01
high      1.214203e+01
low       1.202455e+01
close     1.213383e+01
volume    2.702746e+08
Name: 2011-11-07 14:30:00, dtype: float64

In [110]:
df['low_high_avg'] = (df['low'] + df['high'] / 2)
df

,open,high,low,close,volume,low_high_avg
time,,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0,18.071286
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0,18.123800
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0,18.239751
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0,18.095565
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0,18.381818
...,...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0,270.510500
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0,267.490000
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0,267.925000
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0,267.880000
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0,271.745000

In [111]:
df.loc[df['open'] == 0]

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,0.0,25.306911,24.784321,25.172889,208258972.0,37.437776

In [112]:
df.loc[df['open'] == 0, 'open'] = df['low_high_avg']  # This will set the 'open' value to the average of 'low' and 'high' for rows where 'open' is equal to 0.

In [113]:
df.loc[df['open'] == 0]

Empty DataFrame
Columns: [open, high, low, close, volume, low_high_avg]
Index: []

In [114]:
df.loc['2015-10-05']

,open,high,low,close,volume,low_high_avg
time,,,,,,
2015-10-05 13:30:00,37.437776,25.306911,24.784321,25.172889,208258972.0,37.437776

In [115]:
df.describe()

,open,high,low,close,volume,low_high_avg
count,2919.000000,2919.000000,2919.000000,2919.000000,2.919000e+03,2919.000000
mean,59.713811,60.381601,59.070005,59.754203,2.005580e+08,89.260805
std,51.253308,51.904884,50.655862,51.312979,1.710356e+08,76.605531
min,11.183412,11.266281,11.028606,11.036195,3.519586e+07,16.661747
25%,21.840326,22.090857,21.619382,21.852009,9.176624e+07,32.653514
50%,36.510268,36.724498,36.178549,36.576141,1.371484e+08,54.620716
75%,93.357071,94.554869,92.273407,93.840608,2.479762e+08,139.622636
max,182.630000,184.951000,180.630000,180.960000,1.506113e+09,271.745000

In [118]:
mean_prices = df["close"].mean()
median_prices = df["close"].median()
std_prices = df["close"].std()

print("Average closing prices:", round(mean_prices,2), '$')
print("Median closing prices:", median_prices)
print("Standard deviation of closing prices:", std_prices)

Average closing prices: 59.75 $
Median closing prices: 36.57614127
Standard deviation of closing prices: 51.312979089193696

In [120]:
# Creating a moving average of the closing prices with a window of 9 days

df['close_ma'] = df['close'].rolling(window=9).mean()
df

,open,high,low,close,volume,low_high_avg,close_ma
time,,,,,,,
2011-11-02 13:30:00,12.144762,12.155382,11.993595,12.063406,328255052.0,18.071286,NaN
2011-11-03 13:30:00,12.113800,12.245232,12.001184,12.235220,441524796.0,18.123800,NaN
2011-11-04 13:30:00,12.203650,12.246448,12.116527,12.149313,302228240.0,18.239751,NaN
2011-11-07 14:30:00,12.139294,12.142028,12.024551,12.133831,270274636.0,18.095565,NaN
2011-11-08 14:30:00,12.209111,12.384869,12.189383,12.331139,400439768.0,18.381818,NaN
...,...,...,...,...,...,...,...
2023-06-05 13:30:00,182.630000,184.951000,178.035000,179.580000,121946497.0,270.510500,176.332222
2023-06-06 13:30:00,179.965000,180.120000,177.430000,179.210000,64848374.0,267.490000,177.182222
2023-06-07 13:30:00,178.440000,181.210000,177.320000,177.820000,61944615.0,267.925000,177.846667
2023-06-08 13:30:00,177.895000,180.840000,177.460000,180.570000,50214881.0,267.880000,178.688889
2023-06-09 13:30:00,181.500000,182.230000,180.630000,180.960000,48899973.0,271.745000,179.303333

In [121]:
df.describe()  #

,open,high,low,close,volume,low_high_avg,close_ma
count,2919.000000,2919.000000,2919.000000,2919.000000,2.919000e+03,2919.000000,2911.000000
mean,59.713811,60.381601,59.070005,59.754203,2.005580e+08,89.260805,59.654694
std,51.253308,51.904884,50.655862,51.312979,1.710356e+08,76.605531,51.129528
min,11.183412,11.266281,11.028606,11.036195,3.519586e+07,16.661747,11.332391
25%,21.840326,22.090857,21.619382,21.852009,9.176624e+07,32.653514,21.949145
50%,36.510268,36.724498,36.178549,36.576141,1.371484e+08,54.620716,36.526475
75%,93.357071,94.554869,92.273407,93.840608,2.479762e+08,139.622636,93.781973
max,182.630000,184.951000,180.630000,180.960000,1.506113e+09,271.745000,179.303333

In [137]:
# Creating a new column 'daily_return' that calculates the daily return of the stock based on the 'close' price.

df['daily_return'] = df['close'].pct_change()  # This will calculate the daily return as the percentage change in the 'close' price from the previous day.
df['volatility'] = df['daily_return'].rolling(30).std()  # This will calculate the rolling standard deviation of the 'daily_return' over a window of 30 days, which is a measure of volatility.
df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility
time,,,,,,,,,
2011-11-02 13:30:00,12.1448,12.1554,11.9936,12.0634,328255052.0000,18.0713,NaN,NaN,NaN
2011-11-03 13:30:00,12.1138,12.2452,12.0012,12.2352,441524796.0000,18.1238,NaN,0.0142,NaN
2011-11-04 13:30:00,12.2036,12.2464,12.1165,12.1493,302228240.0000,18.2398,NaN,-0.0070,NaN
2011-11-07 14:30:00,12.1393,12.1420,12.0246,12.1338,270274636.0000,18.0956,NaN,-0.0013,NaN
2011-11-08 14:30:00,12.2091,12.3849,12.1894,12.3311,400439768.0000,18.3818,NaN,0.0163,NaN
...,...,...,...,...,...,...,...,...,...
2023-06-05 13:30:00,182.6300,184.9510,178.0350,179.5800,121946497.0000,270.5105,176.3322,-0.0076,0.0124
2023-06-06 13:30:00,179.9650,180.1200,177.4300,179.2100,64848374.0000,267.4900,177.1822,-0.0021,0.0125
2023-06-07 13:30:00,178.4400,181.2100,177.3200,177.8200,61944615.0000,267.9250,177.8467,-0.0078,0.0124
2023-06-08 13:30:00,177.8950,180.8400,177.4600,180.5700,50214881.0000,267.8800,178.6889,0.0155,0.0126
2023-06-09 13:30:00,181.5000,182.2300,180.6300,180.9600,48899973.0000,271.7450,179.3033,0.0022,0.0117

In [141]:
# Sorting the DataFrame by a column colatility in descending order to see the most volatile days at the top.

df.sort_values(by='daily_return', ascending=True, inplace=True) # This will sort the DataFrame by the 'daily_return' column in ascending order, modifying it in place.

df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility
time,,,,,,,,,
2020-03-16 13:30:00,59.2264,63.4196,58.7491,59.2901,322423460.0000,90.4589,67.4537,-0.1286,0.0513
2013-01-24 14:30:00,14.0873,14.2628,13.7887,13.7964,1460853300.0000,20.9201,15.2647,-0.1235,0.0307
2019-01-03 14:30:00,34.6406,35.0593,34.1642,34.2100,365248780.0000,51.6939,36.9388,-0.0996,0.0312
2020-03-12 13:30:00,62.6510,66.0927,60.7074,60.7637,418474068.0000,93.7537,69.3019,-0.0988,0.0402
2020-09-03 13:30:00,124.8251,126.7234,118.5204,118.8942,257599640.0000,181.8821,124.8615,-0.0801,0.0311
...,...,...,...,...,...,...,...,...,...
2020-03-02 14:30:00,69.0987,73.7888,67.9825,73.1450,341397356.0000,104.8769,72.9351,0.0931,0.0289
2020-03-24 13:30:00,57.8580,60.6315,57.3538,60.4332,287531092.0000,87.6695,60.1963,0.1003,0.0562
2020-07-31 13:30:00,101.0114,104.4784,98.9902,104.3263,374295468.0000,151.2294,94.3931,0.1047,0.0254
2020-03-13 13:30:00,64.8418,68.5210,61.9191,68.0437,370732128.0000,96.1796,68.7351,0.1198,0.0464
2011-11-02 13:30:00,12.1448,12.1554,11.9936,12.0634,328255052.0000,18.0713,NaN,NaN,NaN

In [147]:
df['change'] = (df['close'] - df['open']) / df['close'] 
df.sort_values(by='change', ascending=True, inplace=True) # This will sort the DataFrame by the 'change' column in ascending order, modifying it in place.

df

,open,high,low,close,volume,low_high_avg,close_ma,daily_return,volatility,change
time,,,,,,,,,,
2015-10-05 13:30:00,37.4378,25.3069,24.7843,25.1729,208258972.0000,37.4378,25.4140,0.0036,0.0217,-0.4872
2020-03-20 13:30:00,60.5066,61.6449,55.8116,56.1152,401693384.0000,86.6341,62.6311,-0.0635,0.0525,-0.0783
2015-08-25 13:30:00,25.2479,25.2479,23.5186,23.5732,414406396.0000,36.1426,25.3756,0.0060,0.0211,-0.0710
2020-09-10 13:30:00,118.3827,118.5204,110.6518,111.6256,182274391.0000,169.9121,120.7496,-0.0326,0.0349,-0.0605
2012-12-05 14:30:00,17.4227,17.4331,16.4996,16.5003,1044638484.0000,25.2162,17.7086,-0.0643,0.0256,-0.0559
...,...,...,...,...,...,...,...,...,...,...
2022-10-13 13:30:00,134.3751,142.9360,133.7579,142.3387,113223975.0000,205.2259,141.7071,0.0336,0.0230,0.0559
2018-12-26 14:30:00,35.6800,37.8285,35.2998,37.8140,234330176.0000,54.2141,38.4653,0.0704,0.0282,0.0564
2020-02-28 14:30:00,62.9741,68.1514,62.7562,66.9152,426884920.0000,96.8319,73.4842,-0.0006,0.0229,0.0589
2022-02-24 14:30:00,151.4518,161.6459,150.8761,161.5367,141147540.0000,231.6990,166.1148,0.0167,0.0196,0.0624
2015-08-24 13:30:00,21.5576,24.7230,20.9055,23.4323,648825168.0000,33.2669,25.6660,-0.0250,0.0210,0.0800

In [148]:
# Importing CVS into new df with pandas

df_t = pd.read_csv('TITANIC.csv')  # This will read the CSV file 'TITANIC.csv' into a new DataFrame df_t.

df_t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0000,0,0,370376,7.7500,NaN,Q

In [149]:
df_t.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0000,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0000,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0000,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0000,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0000,1,0,237736,30.0708,NaN,C

In [150]:
# Determine the dataset's dimensions (i.e. the number of rows and columns).

df_t.shape  # This will return a tuple representing the dimensions of the DataFrame, where the first element is the number of rows and the second element is the number of columns.

(891, 12)

In [151]:
# Count the number of passengers in each class (Pclass).

df_t['Pclass'].value_counts()  # This will return a Series containing counts of unique values in the 'Pclass' column, effectively counting the number of passengers in each class.

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [152]:
average_age = df_t['Age'].mean()  # This will calculate the average age of passengers in the Titanic dataset.
average_age

np.float64(29.69911764705882)

In [155]:
df_t.sort_values(by='Age', ascending=False, inplace=True)
df_t

#Oldest - Barkworth, Mr. Algernon Henry Wilson

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0000,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0000,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5000,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [156]:
df_t.sort_values(by='Age', ascending=True, inplace=True)
df_t

# Youngest - Thomas, Master. Assad Alexander

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.4200,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.6700,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.7500,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.7500,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.8300,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [157]:
df_t['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [158]:
df_t['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [159]:
# Calculate How many men and women survived?

men_survived = df_t[(df_t['Sex'] == 'male') & (df_t['Survived'] == 1)].shape[0]  # This will count the number of male passengers who survived.
men_survived

109

In [161]:
women_survived = df_t[(df_t['Sex'] == 'female') & (df_t['Survived'] == 1)].shape[0]
women_survived

233

In [162]:
women_survived1 = len(df_t[(df_t['Sex'] == 'female') & (df_t['Survived'] == 1)])
women_survived1

233

In [176]:
first_class_survival_rate = df_t[df_t['Pclass'] == 1]['Survived'].mean()  
print(first_class_survival_rate)

second_class_survival_rate = df_t[df_t['Pclass'] == 2]['Survived'].mean()
print(second_class_survival_rate)

third_class_survival_rate = df_t[df_t['Pclass'] == 3]['Survived'].mean()
print(third_class_survival_rate)

0.6296296296296297
0.47282608695652173
0.24236252545824846

In [177]:


first_class_total = len(df_t['Pclass'] == 1)
print(first_class_total)

first_class_survived = len(df_t[(df_t['Pclass'] == 1) & (df_t['Survived'] == 1)])
print(first_class_survived)

first_class_survival_rate2 = first_class_survived / first_class_total
print(first_class_survival_rate2)

891
136
0.1526374859708193

In [174]:
first_class_survival_rate = df_t[df_t['Pclass'] == 1]['Survived']
first_class_survival_rate

305    1
297    0
445    1
802    1
435    1
      ..
766    0
793    0
815    0
839    1
849    1
Name: Survived, Length: 216, dtype: int64

In [178]:
df_t['FamilySize'] = df_t['SibSp'] + df_t['Parch']
df_t

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.4200,0,1,2625,8.5167,NaN,C,1
755,756,1,2,"Hamalainen, Master. Viljo",male,0.6700,1,1,250649,14.5000,NaN,S,2
644,645,1,3,"Baclini, Miss. Eugenie",female,0.7500,2,1,2666,19.2583,NaN,C,3
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.7500,2,1,2666,19.2583,NaN,C,3
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.8300,0,2,248738,29.0000,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,0
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,0
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3

In [191]:
df_t[df_t['Survived'] == 0].sort_values(by='FamilySize', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,266,0,2,"Reeves, Mr. David",male,36.0000,0,0,C.A. 17248,10.5000,NaN,S,0
292,293,0,2,"Levy, Mr. Rene Jacques",male,36.0000,0,0,SC/Paris 2163,12.8750,D,C,0
614,615,0,3,"Brocklebank, Mr. William Alfred",male,35.0000,0,0,364512,8.0500,NaN,S,0
812,813,0,2,"Slemen, Mr. Richard James",male,35.0000,0,0,28206,10.5000,NaN,S,0
800,801,0,2,"Ponesell, Mr. Martin",male,34.0000,0,0,250647,13.0000,NaN,S,0

In [192]:
# Clean alternative using .query()
df_t.query('Survived == 0').sort_values(by='FamilySize', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
324,325,0,3,"Sage, Mr. George John Jr",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
201,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.5500,NaN,S,10
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,266,0,2,"Reeves, Mr. David",male,36.0000,0,0,C.A. 17248,10.5000,NaN,S,0
292,293,0,2,"Levy, Mr. Rene Jacques",male,36.0000,0,0,SC/Paris 2163,12.8750,D,C,0
614,615,0,3,"Brocklebank, Mr. William Alfred",male,35.0000,0,0,364512,8.0500,NaN,S,0
812,813,0,2,"Slemen, Mr. Richard James",male,35.0000,0,0,28206,10.5000,NaN,S,0
800,801,0,2,"Ponesell, Mr. Martin",male,34.0000,0,0,250647,13.0000,NaN,S,0