In [49]:
import pandas as pd
import datetime

In [50]:
df = pd.read_csv('BTC-USDT.csv')
df

                date      open      high       low     close       volume
0      1502942400000   4261.48   4313.62   4261.32   4308.83    47.181009
1      1502946000000   4308.83   4328.69   4291.37   4315.32    23.234916
2      1502949600000   4330.29   4345.45   4309.37   4324.35     7.229691
3      1502953200000   4316.62   4349.99   4287.41   4349.99     4.443249
4      1502956800000   4333.32   4377.85   4333.32   4360.69     0.972807
...              ...       ...       ...       ...       ...          ...
51404  1688364000000  30673.61  30678.41  30606.00  30651.25  1036.522350
51405  1688367600000  30651.25  30759.80  30636.65  30667.19  1758.796390
51406  1688371200000  30667.19  30700.92  30599.07  30640.12  1390.909010
51407  1688374800000  30640.11  30670.00  30602.29  30610.61   833.620010
51408  1688378400000  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 6 columns]

In [51]:
df['date'] = pd.to_datetime(df['date'], unit='ms', utc=True)
df

,date,open,high,low,close,volume
0,2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009
1,2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916
2,2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691
3,2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249
4,2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807
...,...,...,...,...,...,...
51404,2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350
51405,2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390
51406,2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010
51407,2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010
51408,2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210

In [52]:
#setting the date column as the index of the dataframe
df.set_index('date', inplace=True)
df

                               open      high       low     close       volume
date
2017-08-17 04:00:00+00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00+00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00+00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00+00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00+00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                             ...       ...       ...       ...          ...
2023-07-03 06:00:00+00:00  30673.61  30678.41  30606.00  30651.25  1036.522350
2023-07-03 07:00:00+00:00  30651.25  30759.80  30636.65  30667.19  1758.796390
2023-07-03 08:00:00+00:00  30667.19  30700.92  30599.07  30640.12  1390.909010
2023-07-03 09:00:00+00:00  30640.11  30670.00  30602.29  30610.61   833.620010
2023-07-03 10:00:00+00:00  30610.60  30623.08  30605.66  30615.85    91.875210

[51409 rows x 5 columns]

In [53]:
df['ma50'] = df['close'].rolling(50).mean()
df['ma200'] = df['close'].rolling(200).mean()
df

,open,high,low,close,volume,ma50,ma200
date,,,,,,,
2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN
2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN
2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN
2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN
2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN
...,...,...,...,...,...,...,...
2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635
2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515
2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960
2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005
2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280

In [54]:
df['buy_signal'] = False
df['sell_signal'] = False
df

,open,high,low,close,volume,ma50,ma200,buy_signal,sell_signal
date,,,,,,,,,
2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False
2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False
2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False
2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False
2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635,False,False
2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515,False,False
2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960,False,False
2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005,False,False
2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280,False,False

In [55]:
# Creating buy and sell signals based on moving averages
df.loc[df['ma50'] > df['ma200'], 'buy_signal'] = True
df.loc[df['ma50'] < df['ma200'], 'sell_signal'] = True
df

,open,high,low,close,volume,ma50,ma200,buy_signal,sell_signal
date,,,,,,,,,
2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False
2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False
2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False
2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False
2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635,True,False
2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515,True,False
2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960,True,False
2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005,True,False
2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280,True,False

In [56]:
df['sell_signal'].value_counts()

sell_signal
False    26943
True     24466
Name: count, dtype: int64

In [57]:
balance = 1000
position = None

for index, row in df.iterrows():
    # Check for buy signal
    if position is None and row['buy_signal'] is True:
        buy_price = row['close']
        usd_size = balance
        position = {
            'buy_price': buy_price,
            'usd_size': usd_size
        }
        
        print(f'{index} - Bought Bitcoin for {usd_size} USD at {buy_price} USD')
        
    # Check for sell signal
    if position is not None and row['sell_signal'] is True:
        sell_price = row['close']
        trade_results = (sell_price - position['buy_price']) / position['buy_price'] 
        balance += trade_results * position['usd_size']
        print(f'{index} - Sold Bitcoin for {balance} USD at price of {sell_price} USD ({round(trade_results * 100, 2)}% profit)')
        position = None

2017-08-25 11:00:00+00:00 - Bought Bitcoin for 1000 USD at 4361.27 USD
2017-09-04 06:00:00+00:00 - Sold Bitcoin for 1022.5851644131182 USD at price of 4459.77 USD (2.26% profit)
2017-09-07 21:00:00+00:00 - Bought Bitcoin for 1022.5851644131182 USD at 4641.13 USD
2017-09-09 13:00:00+00:00 - Sold Bitcoin for 947.4588776015138 USD at price of 4300.16 USD (-7.35% profit)
2017-09-19 09:00:00+00:00 - Bought Bitcoin for 947.4588776015138 USD at 3940.2 USD
2017-09-22 21:00:00+00:00 - Sold Bitcoin for 871.4760516705198 USD at price of 3624.21 USD (-8.02% profit)
2017-09-26 13:00:00+00:00 - Bought Bitcoin for 871.4760516705198 USD at 3928.33 USD
2017-10-05 07:00:00+00:00 - Sold Bitcoin for 921.5617492024618 USD at price of 4154.1 USD (5.75% profit)
2017-10-06 17:00:00+00:00 - Bought Bitcoin for 921.5617492024618 USD at 4336.16 USD
2017-10-19 19:00:00+00:00 - Sold Bitcoin for 1192.0777488092249 USD at price of 5609.0 USD (29.35% profit)
2017-10-20 15:00:00+00:00 - Bought Bitcoin for 1192.0777488092249 USD at 5889.99 USD
2017-10-25 02:00:00+00:00 - Sold Bitcoin for 1072.4670145348434 USD at price of 5299.0 USD (-10.03% profit)
2017-10-27 21:00:00+00:00 - Bought Bitcoin for 1072.4670145348434 USD at 5769.6 USD
2017-10-28 17:00:00+00:00 - Sold Bitcoin for 1059.5983769488328 USD at price of 5700.37 USD (-1.2% profit)
2017-10-29 21:00:00+00:00 - Bought Bitcoin for 1059.5983769488328 USD at 6132.59 USD
2017-11-10 12:00:00+00:00 - Sold Bitcoin for 1145.5381897702637 USD at price of 6629.98 USD (8.11% profit)
2017-11-15 22:00:00+00:00 - Bought Bitcoin for 1145.5381897702637 USD at 7200.43 USD
2017-12-20 21:00:00+00:00 - Sold Bitcoin for 2590.034446478876 USD at price of 16280.0 USD (126.1% profit)
2017-12-27 12:00:00+00:00 - Bought Bitcoin for 2590.034446478876 USD at 15894.83 USD
2017-12-30 03:00:00+00:00 - Sold Bitcoin for 2187.358405036839 USD at price of 13423.64 USD (-15.55% profit)
2018-01-03 18:00:00+00:00 - Bought Bitcoin for 2187.358405036839 USD at 14749.97 USD
2018-01-09 19:00:00+00:00 - Sold Bitcoin for 2182.590695494248 USD at price of 14717.82 USD (-0.22% profit)
2018-01-22 00:00:00+00:00 - Bought Bitcoin for 2182.590695494248 USD at 11750.11 USD
2018-01-22 14:00:00+00:00 - Sold Bitcoin for 1971.1878685809677 USD at price of 10612.01 USD (-9.69% profit)
2018-01-28 13:00:00+00:00 - Bought Bitcoin for 1971.1878685809677 USD at 11850.13 USD
2018-01-30 23:00:00+00:00 - Sold Bitcoin for 1702.9395893949134 USD at price of 10237.51 USD (-13.61% profit)
2018-02-10 17:00:00+00:00 - Bought Bitcoin for 1702.9395893949134 USD at 8391.92 USD
2018-02-23 00:00:00+00:00 - Sold Bitcoin for 1956.5708328525513 USD at price of 9641.79 USD (14.89% profit)
2018-02-28 05:00:00+00:00 - Bought Bitcoin for 1956.5708328525513 USD at 10947.66 USD
2018-03-07 16:00:00+00:00 - Sold Bitcoin for 1771.123334574278 USD at price of 9910.02 USD (-9.48% profit)
2018-03-20 21:00:00+00:00 - Bought Bitcoin for 1771.123334574278 USD at 8987.01 USD
2018-03-26 13:00:00+00:00 - Sold Bitcoin for 1595.3296361502635 USD at price of 8095.0 USD (-9.93% profit)
2018-04-09 00:00:00+00:00 - Bought Bitcoin for 1595.3296361502635 USD at 7060.0 USD
2018-04-10 00:00:00+00:00 - Sold Bitcoin for 1528.8071019312442 USD at price of 6765.61 USD (-4.17% profit)
2018-04-12 10:00:00+00:00 - Bought Bitcoin for 1528.8071019312442 USD at 6935.1 USD
2018-05-01 19:00:00+00:00 - Sold Bitcoin for 1979.4889688589417 USD at price of 8979.52 USD (29.48% profit)
2018-05-03 16:00:00+00:00 - Bought Bitcoin for 1979.4889688589417 USD at 9613.12 USD
2018-05-08 11:00:00+00:00 - Sold Bitcoin for 1894.0093887899604 USD at price of 9198.0 USD (-4.32% profit)
2018-05-21 12:00:00+00:00 - Bought Bitcoin for 1894.0093887899604 USD at 8493.71 USD
2018-05-23 01:00:00+00:00 - Sold Bitcoin for 1763.2861684315615 USD at price of 7907.48 USD (-6.9% profit)
2018-05-31 11:00:00+00:00 - Bought Bitcoin for 1763.2861684315615 USD at 7531.97 USD
2018-06-06 14:00:00+00:00 - Sold Bitcoin for 1784.704608965685 USD at price of 7623.46 USD (1.21% profit)
2018-06-06 15:00:00+00:00 - Bought Bitcoin for 1784.704608965685 USD at 7650.5 USD
2018-06-06 16:00:00+00:00 - Sold Bitcoin for 1753.5594665118574 USD at price of 7516.99 USD (-1.75% profit)
2018-06-06 21:00:00+00:00 - Bought Bitcoin for 1753.5594665118574 USD at 7664.99 USD
2018-06-10 02:00:00+00:00 - Sold Bitcoin for 1674.8791066258357 USD at price of 7321.07 USD (-4.49% profit)
2018-06-19 12:00:00+00:00 - Bought Bitcoin for 1674.8791066258357 USD at 6765.82 USD
2018-06-22 22:00:00+00:00 - Sold Bitcoin for 1502.893706581451 USD at price of 6071.07 USD (-10.27% profit)
2018-06-30 23:00:00+00:00 - Bought Bitcoin for 1502.893706581451 USD at 6390.07 USD
2018-07-10 23:00:00+00:00 - Sold Bitcoin for 1480.983214567259 USD at price of 6296.91 USD (-1.46% profit)
2018-07-16 21:00:00+00:00 - Bought Bitcoin for 1480.983214567259 USD at 6665.6 USD
2018-07-31 16:00:00+00:00 - Sold Bitcoin for 1734.8962047616315 USD at price of 7808.41 USD (17.14% profit)
2018-08-16 16:00:00+00:00 - Bought Bitcoin for 1734.8962047616315 USD at 6391.51 USD
2018-09-06 07:00:00+00:00 - Sold Bitcoin for 1738.7967632309799 USD at price of 6405.88 USD (0.22% profit)
2018-09-14 03:00:00+00:00 - Bought Bitcoin for 1738.7967632309799 USD at 6542.37 USD
2018-09-18 10:00:00+00:00 - Sold Bitcoin for 1661.0735948013028 USD at price of 6249.93 USD (-4.47% profit)
2018-09-21 11:00:00+00:00 - Bought Bitcoin for 1661.0735948013028 USD at 6742.23 USD
2018-09-26 03:00:00+00:00 - Sold Bitcoin for 1574.418376053283 USD at price of 6390.5 USD (-5.22% profit)
2018-09-28 22:00:00+00:00 - Bought Bitcoin for 1574.418376053283 USD at 6633.81 USD
2018-10-03 14:00:00+00:00 - Sold Bitcoin for 1550.0300935545024 USD at price of 6531.05 USD (-1.55% profit)
2018-10-06 00:00:00+00:00 - Bought Bitcoin for 1550.0300935545024 USD at 6624.47 USD
2018-10-11 07:00:00+00:00 - Sold Bitcoin for 1474.3100376745342 USD at price of 6300.86 USD (-4.89% profit)
2018-10-15 16:00:00+00:00 - Bought Bitcoin for 1474.3100376745342 USD at 6927.49 USD
2018-10-20 22:00:00+00:00 - Sold Bitcoin for 1402.4874653554978 USD at price of 6590.01 USD (-4.87% profit)
2018-11-04 23:00:00+00:00 - Bought Bitcoin for 1402.4874653554978 USD at 6485.85 USD
2018-11-10 12:00:00+00:00 - Sold Bitcoin for 1395.9224785845743 USD at price of 6455.49 USD (-0.47% profit)
2018-11-30 00:00:00+00:00 - Bought Bitcoin for 1395.9224785845743 USD at 4242.99 USD
2018-12-04 02:00:00+00:00 - Sold Bitcoin for 1279.997801751949 USD at price of 3890.63 USD (-8.3% profit)
2018-12-18 10:00:00+00:00 - Bought Bitcoin for 1279.997801751949 USD at 3474.0 USD
2018-12-26 10:00:00+00:00 - Sold Bitcoin for 1371.0567127263234 USD at price of 3721.14 USD (7.11% profit)
2019-01-02 19:00:00+00:00 - Bought Bitcoin for 1371.0567127263234 USD at 3824.98 USD
2019-01-11 01:00:00+00:00 - Sold Bitcoin for 1287.8860061987366 USD at price of 3592.95 USD (-6.07% profit)
2019-01-18 12:00:00+00:00 - Bought Bitcoin for 1287.8860061987366 USD at 3589.3 USD
2019-01-21 19:00:00+00:00 - Sold Bitcoin for 1266.1850211445758 USD at price of 3528.82 USD (-1.69% profit)
2019-01-27 20:00:00+00:00 - Bought Bitcoin for 1266.1850211445758 USD at 3568.68 USD
2019-01-28 05:00:00+00:00 - Sold Bitcoin for 1219.8971786205834 USD at price of 3438.22 USD (-3.66% profit)
2019-02-03 19:00:00+00:00 - Bought Bitcoin for 1219.8971786205834 USD at 3445.6 USD
2019-02-06 15:00:00+00:00 - Sold Bitcoin for 1211.5487993914583 USD at price of 3422.02 USD (-0.68% profit)
2019-02-09 00:00:00+00:00 - Bought Bitcoin for 1211.5487993914583 USD at 3654.84 USD
2019-02-16 02:00:00+00:00 - Sold Bitcoin for 1197.7587483756313 USD at price of 3613.24 USD (-1.14% profit)
2019-02-17 22:00:00+00:00 - Bought Bitcoin for 1197.7587483756313 USD at 3641.27 USD
2019-02-26 00:00:00+00:00 - Sold Bitcoin for 1259.8954829677261 USD at price of 3830.17 USD (5.19% profit)
2019-03-06 22:00:00+00:00 - Bought Bitcoin for 1259.8954829677261 USD at 3865.41 USD
2019-03-13 15:00:00+00:00 - Sold Bitcoin for 1262.043433956821 USD at price of 3872.0 USD (0.17% profit)
2019-03-16 01:00:00+00:00 - Bought Bitcoin for 1262.043433956821 USD at 3960.01 USD
2019-03-23 14:00:00+00:00 - Sold Bitcoin for 1271.6011579485191 USD at price of 3990.0 USD (0.76% profit)
2019-03-28 12:00:00+00:00 - Bought Bitcoin for 1271.6011579485191 USD at 4016.56 USD
2019-04-12 18:00:00+00:00 - Sold Bitcoin for 1593.4556516459124 USD at price of 5033.19 USD (25.31% profit)
2019-04-17 08:00:00+00:00 - Bought Bitcoin for 1593.4556516459124 USD at 5169.67 USD
2019-04-27 09:00:00+00:00 - Sold Bitcoin for 1627.1546123908822 USD at price of 5279.0 USD (2.11% profit)
2019-05-02 07:00:00+00:00 - Bought Bitcoin for 1627.1546123908822 USD at 5406.31 USD
2019-05-18 20:00:00+00:00 - Sold Bitcoin for 2194.293528557132 USD at price of 7290.66 USD (34.85% profit)
2019-05-19 18:00:00+00:00 - Bought Bitcoin for 2194.293528557132 USD at 7974.23 USD
2019-06-01 21:00:00+00:00 - Sold Bitcoin for 2362.1353562625563 USD at price of 8584.18 USD (7.65% profit)
2019-06-01 23:00:00+00:00 - Bought Bitcoin for 2362.1353562625563 USD at 8544.07 USD
2019-06-04 00:00:00+00:00 - Sold Bitcoin for 2208.437466385647 USD at price of 7988.13 USD (-6.51% profit)
2019-06-12 03:00:00+00:00 - Bought Bitcoin for 2208.437466385647 USD at 7959.76 USD
2019-07-01 08:00:00+00:00 - Sold Bitcoin for 3101.3611810225525 USD at price of 11178.08 USD (40.43% profit)
2019-07-05 00:00:00+00:00 - Bought Bitcoin for 3101.3611810225525 USD at 11170.81 USD
2019-07-06 13:00:00+00:00 - Sold Bitcoin for 3147.5006476032336 USD at price of 11337.0 USD (1.49% profit)
2019-07-07 08:00:00+00:00 - Bought Bitcoin for 3147.5006476032336 USD at 11185.4 USD
2019-07-12 14:00:00+00:00 - Sold Bitcoin for 3259.557230996636 USD at price of 11583.62 USD (3.56% profit)
2019-07-20 19:00:00+00:00 - Bought Bitcoin for 3259.557230996636 USD at 10898.66 USD
2019-07-23 22:00:00+00:00 - Sold Bitcoin for 3000.0705560515235 USD at price of 10031.04 USD (-7.96% profit)
2019-08-01 03:00:00+00:00 - Bought Bitcoin for 3000.0705560515235 USD at 9988.02 USD
2019-08-11 20:00:00+00:00 - Sold Bitcoin for 3434.695445989212 USD at price of 11435.0 USD (14.49% profit)
2019-08-20 15:00:00+00:00 - Bought Bitcoin for 3434.695445989212 USD at 10744.54 USD
2019-08-22 04:00:00+00:00 - Sold Bitcoin for 3188.492840890067 USD at price of 9974.36 USD (-7.17% profit)
2019-09-03 06:00:00+00:00 - Bought Bitcoin for 3188.492840890067 USD at 10375.67 USD
2019-09-09 22:00:00+00:00 - Sold Bitcoin for 3175.475411004565 USD at price of 10333.31 USD (-0.41% profit)
2019-09-14 15:00:00+00:00 - Bought Bitcoin for 3175.475411004565 USD at 10356.32 USD
2019-09-17 15:00:00+00:00 - Sold Bitcoin for 3127.72823527017 USD at price of 10200.6 USD (-1.5% profit)
2019-10-02 14:00:00+00:00 - Bought Bitcoin for 3127.72823527017 USD at 8236.44 USD
2019-10-05 07:00:00+00:00 - Sold Bitcoin for 3078.954078651764 USD at price of 8108.0 USD (-1.56% profit)
2019-10-09 07:00:00+00:00 - Bought Bitcoin for 3078.954078651764 USD at 8179.6 USD
2019-10-15 13:00:00+00:00 - Sold Bitcoin for 3123.9586937482973 USD at price of 8299.16 USD (1.46% profit)
2019-10-22 00:00:00+00:00 - Bought Bitcoin for 3123.9586937482973 USD at 8185.3 USD
2019-10-23 18:00:00+00:00 - Sold Bitcoin for 2864.8456451905663 USD at price of 7506.38 USD (-8.29% profit)
2019-10-26 07:00:00+00:00 - Bought Bitcoin for 2864.8456451905663 USD at 9481.47 USD
2019-11-02 15:00:00+00:00 - Sold Bitcoin for 2817.3745358250476 USD at price of 9324.36 USD (-1.66% profit)
2019-11-05 13:00:00+00:00 - Bought Bitcoin for 2817.3745358250476 USD at 9237.82 USD
2019-11-08 13:00:00+00:00 - Sold Bitcoin for 2687.076811584855 USD at price of 8810.59 USD (-4.62% profit)
2019-11-28 21:00:00+00:00 - Bought Bitcoin for 2687.076811584855 USD at 7548.39 USD
2019-12-02 23:00:00+00:00 - Sold Bitcoin for 2596.6187021612786 USD at price of 7294.28 USD (-3.37% profit)
2019-12-07 07:00:00+00:00 - Bought Bitcoin for 2596.6187021612786 USD at 7521.48 USD
2019-12-11 00:00:00+00:00 - Sold Bitcoin for 2499.2335904953998 USD at price of 7239.39 USD (-3.75% profit)
2019-12-20 10:00:00+00:00 - Bought Bitcoin for 2499.2335904953998 USD at 7144.94 USD
2019-12-26 21:00:00+00:00 - Sold Bitcoin for 2518.4545896637237 USD at price of 7199.89 USD (0.77% profit)
2019-12-29 03:00:00+00:00 - Bought Bitcoin for 2518.4545896637237 USD at 7307.27 USD
2019-12-31 22:00:00+00:00 - Sold Bitcoin for 2481.6493579383064 USD at price of 7200.48 USD (-1.46% profit)
2020-01-04 22:00:00+00:00 - Bought Bitcoin for 2481.6493579383064 USD at 7350.24 USD
2020-01-21 09:00:00+00:00 - Sold Bitcoin for 2913.803509187829 USD at price of 8630.21 USD (17.41% profit)
2020-01-27 19:00:00+00:00 - Bought Bitcoin for 2913.803509187829 USD at 8932.12 USD
2020-02-04 22:00:00+00:00 - Sold Bitcoin for 3001.9993593044887 USD at price of 9202.48 USD (3.03% profit)
2020-02-06 06:00:00+00:00 - Bought Bitcoin for 3001.9993593044887 USD at 9649.07 USD
2020-02-16 17:00:00+00:00 - Sold Bitcoin for 3034.9654225739964 USD at price of 9755.03 USD (1.1% profit)
2020-02-24 11:00:00+00:00 - Bought Bitcoin for 3034.9654225739964 USD at 9811.38 USD
2020-02-25 09:00:00+00:00 - Sold Bitcoin for 2957.6264493661556 USD at price of 9561.36 USD (-2.55% profit)
2020-03-05 02:00:00+00:00 - Bought Bitcoin for 2957.6264493661556 USD at 8919.89 USD
2020-03-08 23:00:00+00:00 - Sold Bitcoin for 2663.6573020471815 USD at price of 8033.31 USD (-9.94% profit)
2020-03-20 02:00:00+00:00 - Bought Bitcoin for 2663.6573020471815 USD at 6150.04 USD
2020-03-29 05:00:00+00:00 - Sold Bitcoin for 2662.2150384495762 USD at price of 6146.71 USD (-0.05% profit)
2020-04-02 12:00:00+00:00 - Bought Bitcoin for 2662.2150384495762 USD at 6656.76 USD
2020-04-11 12:00:00+00:00 - Sold Bitcoin for 2749.3190403024773 USD at price of 6874.56 USD (3.27% profit)
2020-04-17 15:00:00+00:00 - Bought Bitcoin for 2749.3190403024773 USD at 7037.94 USD
2020-04-21 21:00:00+00:00 - Sold Bitcoin for 2690.7460918398656 USD at price of 6888.0 USD (-2.13% profit)
2020-04-23 14:00:00+00:00 - Bought Bitcoin for 2690.7460918398656 USD at 7536.36 USD
2020-05-11 01:00:00+00:00 - Sold Bitcoin for 3110.994419600232 USD at price of 8713.41 USD (15.62% profit)
2020-05-14 20:00:00+00:00 - Bought Bitcoin for 3110.994419600232 USD at 9655.88 USD
2020-05-21 18:00:00+00:00 - Sold Bitcoin for 2845.312967646527 USD at price of 8831.26 USD (-8.54% profit)
2020-05-28 20:00:00+00:00 - Bought Bitcoin for 2845.312967646527 USD at 9450.18 USD
2020-06-07 14:00:00+00:00 - Sold Bitcoin for 2846.5925813800745 USD at price of 9454.43 USD (0.04% profit)
2020-06-08 20:00:00+00:00 - Bought Bitcoin for 2846.5925813800745 USD at 9701.69 USD
2020-06-08 22:00:00+00:00 - Sold Bitcoin for 2844.6296548827904 USD at price of 9695.0 USD (-0.07% profit)
2020-06-08 23:00:00+00:00 - Bought Bitcoin for 2844.6296548827904 USD at 9782.01 USD
2020-06-09 01:00:00+00:00 - Sold Bitcoin for 2820.3389503064955 USD at price of 9698.48 USD (-0.85% profit)
2020-06-09 14:00:00+00:00 - Bought Bitcoin for 2820.3389503064955 USD at 9713.76 USD
2020-06-12 02:00:00+00:00 - Sold Bitcoin for 2717.185277345161 USD at price of 9358.48 USD (-3.66% profit)
2020-06-22 17:00:00+00:00 - Bought Bitcoin for 2717.185277345161 USD at 9587.21 USD
2020-06-25 16:00:00+00:00 - Sold Bitcoin for 2632.803317147776 USD at price of 9289.48 USD (-3.11% profit)
2020-07-02 13:00:00+00:00 - Bought Bitcoin for 2632.803317147776 USD at 9246.92 USD
2020-07-03 18:00:00+00:00 - Sold Bitcoin for 2585.0667946999774 USD at price of 9079.26 USD (-1.81% profit)
2020-07-06 23:00:00+00:00 - Bought Bitcoin for 2585.0667946999774 USD at 9344.2 USD
2020-07-14 04:00:00+00:00 - Sold Bitcoin for 2542.3991664657165 USD at price of 9189.97 USD (-1.65% profit)
2020-07-21 12:00:00+00:00 - Bought Bitcoin for 2542.3991664657165 USD at 9367.57 USD
2020-08-12 14:00:00+00:00 - Sold Bitcoin for 3144.034740287196 USD at price of 11584.32 USD (23.66% profit)
2020-08-15 04:00:00+00:00 - Bought Bitcoin for 3144.034740287196 USD at 11863.65 USD
2020-08-20 15:00:00+00:00 - Sold Bitcoin for 3141.5701089903637 USD at price of 11854.35 USD (-0.08% profit)
2020-08-30 13:00:00+00:00 - Bought Bitcoin for 3141.5701089903637 USD at 11628.01 USD
2020-09-03 15:00:00+00:00 - Sold Bitcoin for 2882.8176706554 USD at price of 10670.28 USD (-8.24% profit)
2020-09-11 14:00:00+00:00 - Bought Bitcoin for 2882.8176706554 USD at 10289.46 USD
2020-09-21 23:00:00+00:00 - Sold Bitcoin for 2918.612433996035 USD at price of 10417.22 USD (1.24% profit)
2020-09-26 17:00:00+00:00 - Bought Bitcoin for 2918.612433996035 USD at 10742.68 USD
2020-10-02 10:00:00+00:00 - Sold Bitcoin for 2842.122568835084 USD at price of 10461.14 USD (-2.62% profit)
2020-10-06 09:00:00+00:00 - Bought Bitcoin for 2842.122568835084 USD at 10746.15 USD
2020-10-08 04:00:00+00:00 - Sold Bitcoin for 2812.027592763864 USD at price of 10632.36 USD (-1.06% profit)
2020-10-08 19:00:00+00:00 - Bought Bitcoin for 2812.027592763864 USD at 10878.83 USD
2020-10-17 20:00:00+00:00 - Sold Bitcoin for 2933.552301989213 USD at price of 11348.97 USD (4.32% profit)
2020-10-19 08:00:00+00:00 - Bought Bitcoin for 2933.552301989213 USD at 11466.39 USD
2020-11-26 20:00:00+00:00 - Sold Bitcoin for 4384.1453429673 USD at price of 17136.33 USD (49.45% profit)
2020-11-30 14:00:00+00:00 - Bought Bitcoin for 4384.1453429673 USD at 19480.8 USD
2020-12-08 17:00:00+00:00 - Sold Bitcoin for 4259.605170523423 USD at price of 18927.41 USD (-2.84% profit)
2020-12-13 20:00:00+00:00 - Bought Bitcoin for 4259.605170523423 USD at 19154.57 USD
2021-01-12 07:00:00+00:00 - Sold Bitcoin for 8097.678978821854 USD at price of 36413.6 USD (90.1% profit)
2021-01-15 10:00:00+00:00 - Bought Bitcoin for 8097.678978821854 USD at 38441.89 USD
2021-01-16 23:00:00+00:00 - Sold Bitcoin for 7582.244080327817 USD at price of 35994.98 USD (-6.37% profit)
2021-01-19 11:00:00+00:00 - Bought Bitcoin for 7582.244080327817 USD at 37266.49 USD
2021-01-20 11:00:00+00:00 - Sold Bitcoin for 7004.352266362061 USD at price of 34426.17 USD (-7.62% profit)
2021-01-29 13:00:00+00:00 - Bought Bitcoin for 7004.352266362061 USD at 38250.03 USD
2021-02-23 20:00:00+00:00 - Sold Bitcoin for 8755.799706300068 USD at price of 47814.5 USD (25.01% profit)
2021-03-03 01:00:00+00:00 - Bought Bitcoin for 8755.799706300068 USD at 48848.63 USD
2021-03-16 22:00:00+00:00 - Sold Bitcoin for 10081.269584741853 USD at price of 56243.43 USD (15.14% profit)
2021-03-19 07:00:00+00:00 - Bought Bitcoin for 10081.269584741853 USD at 57834.04 USD
2021-03-22 16:00:00+00:00 - Sold Bitcoin for 9892.93401437294 USD at price of 56753.6 USD (-1.87% profit)
2021-03-28 17:00:00+00:00 - Bought Bitcoin for 9892.93401437294 USD at 55967.73 USD
2021-04-05 07:00:00+00:00 - Sold Bitcoin for 10119.589847986525 USD at price of 57250.0 USD (2.29% profit)
2021-04-10 08:00:00+00:00 - Bought Bitcoin for 10119.589847986525 USD at 60534.89 USD
2021-04-18 02:00:00+00:00 - Sold Bitcoin for 9830.272864704431 USD at price of 58804.21 USD (-2.86% profit)
2021-04-27 18:00:00+00:00 - Bought Bitcoin for 9830.272864704431 USD at 54960.01 USD
2021-05-05 13:00:00+00:00 - Sold Bitcoin for 10060.497240946956 USD at price of 56247.17 USD (2.34% profit)
2021-05-06 18:00:00+00:00 - Bought Bitcoin for 10060.497240946956 USD at 55753.57 USD
2021-05-11 19:00:00+00:00 - Sold Bitcoin for 10214.845160281786 USD at price of 56608.94 USD (1.53% profit)
2021-05-26 15:00:00+00:00 - Bought Bitcoin for 10214.845160281786 USD at 38758.61 USD
2021-05-28 22:00:00+00:00 - Sold Bitcoin for 9240.510065092476 USD at price of 35061.65 USD (-9.54% profit)
2021-06-03 00:00:00+00:00 - Bought Bitcoin for 9240.510065092476 USD at 37469.31 USD
2021-06-06 06:00:00+00:00 - Sold Bitcoin for 8841.95486575211 USD at price of 35853.21 USD (-4.31% profit)
2021-06-11 04:00:00+00:00 - Bought Bitcoin for 8841.95486575211 USD at 37044.01 USD
2021-06-18 21:00:00+00:00 - Sold Bitcoin for 8509.224011752814 USD at price of 35650.01 USD (-3.76% profit)

In [58]:
print('Our final balance is: ', round(balance, 2), 'USD')

Our final balance is:  7847.25 USD

In [64]:
class BacktestCrossMA:
    def __init__(self) -> None:
        self.df = pd.DataFrame()
        
    def load_data(self, path):
        self.df = pd.read_csv(path)
        self.df['date'] = pd.to_datetime(self.df['date'], unit='ms')
        self.df = self.df.set_index(['date'])
        #del self.df['date']
        
    def populate_indicators(self):
        self.df['ma50'] = self.df['close'].rolling(50).mean()
        self.df['ma200'] = self.df['close'].rolling(200).mean()
    
    def populate_signals(self):
        self.df['buy_signal'] = False
        self.df['sell_signal'] = False
        self.df.loc[(self.df['ma50'] > self.df['ma200']), 'buy_signal'] = True
        self.df.loc[(self.df['ma50'] < self.df['ma200']), 'sell_signal'] = True
        
    def run_backtest(self):
        balance = 1000
        position = None
        asset = 'BTC'
        
        for index, row in self.df.iterrows():
            # Check for buy signal
            if position is None and row['buy_signal']:
                open_price = row['close']
                position = {
                    'open_price' : open_price,
                    'usd_size' : balance,
                }
                
                print(f'{index} - Buy for {balance}$ of {asset} at price : {open_price}$')
                
            elif position is not None and row['sell_signal']:
                close_price = row['close']
                trade_result = (close_price - position['open_price']) / position['open_price']
                balance = balance + trade_result * position['usd_size']
                position = None
                print(f'{index} - Sell for {balance}$ of {asset} at {close_price}$')
                
        print(f'Final balance: {balance}$')

In [65]:
bt = BacktestCrossMA()
bt.load_data('BTC-USDT.csv')
bt.populate_indicators()
bt.populate_signals()
bt.run_backtest()

2017-08-25 11:00:00 - Buy for 1000$ of BTC at price : 4361.27$
2017-09-04 06:00:00 - Sell for 1022.5851644131182$ of BTC at 4459.77$
2017-09-07 21:00:00 - Buy for 1022.5851644131182$ of BTC at price : 4641.13$
2017-09-09 13:00:00 - Sell for 947.4588776015138$ of BTC at 4300.16$
2017-09-19 09:00:00 - Buy for 947.4588776015138$ of BTC at price : 3940.2$
2017-09-22 21:00:00 - Sell for 871.4760516705198$ of BTC at 3624.21$
2017-09-26 13:00:00 - Buy for 871.4760516705198$ of BTC at price : 3928.33$
2017-10-05 07:00:00 - Sell for 921.5617492024618$ of BTC at 4154.1$
2017-10-06 17:00:00 - Buy for 921.5617492024618$ of BTC at price : 4336.16$
2017-10-19 19:00:00 - Sell for 1192.0777488092249$ of BTC at 5609.0$
2017-10-20 15:00:00 - Buy for 1192.0777488092249$ of BTC at price : 5889.99$
2017-10-25 02:00:00 - Sell for 1072.4670145348434$ of BTC at 5299.0$
2017-10-27 21:00:00 - Buy for 1072.4670145348434$ of BTC at price : 5769.6$
2017-10-28 17:00:00 - Sell for 1059.5983769488328$ of BTC at 5700.37$
2017-10-29 21:00:00 - Buy for 1059.5983769488328$ of BTC at price : 6132.59$
2017-11-10 12:00:00 - Sell for 1145.5381897702637$ of BTC at 6629.98$
2017-11-15 22:00:00 - Buy for 1145.5381897702637$ of BTC at price : 7200.43$
2017-12-20 21:00:00 - Sell for 2590.034446478876$ of BTC at 16280.0$
2017-12-27 12:00:00 - Buy for 2590.034446478876$ of BTC at price : 15894.83$
2017-12-30 03:00:00 - Sell for 2187.358405036839$ of BTC at 13423.64$
2018-01-03 18:00:00 - Buy for 2187.358405036839$ of BTC at price : 14749.97$
2018-01-09 19:00:00 - Sell for 2182.590695494248$ of BTC at 14717.82$
2018-01-22 00:00:00 - Buy for 2182.590695494248$ of BTC at price : 11750.11$
2018-01-22 14:00:00 - Sell for 1971.1878685809677$ of BTC at 10612.01$
2018-01-28 13:00:00 - Buy for 1971.1878685809677$ of BTC at price : 11850.13$
2018-01-30 23:00:00 - Sell for 1702.9395893949134$ of BTC at 10237.51$
2018-02-10 17:00:00 - Buy for 1702.9395893949134$ of BTC at price : 8391.92$
2018-02-23 00:00:00 - Sell for 1956.5708328525513$ of BTC at 9641.79$
2018-02-28 05:00:00 - Buy for 1956.5708328525513$ of BTC at price : 10947.66$
2018-03-07 16:00:00 - Sell for 1771.123334574278$ of BTC at 9910.02$
2018-03-20 21:00:00 - Buy for 1771.123334574278$ of BTC at price : 8987.01$
2018-03-26 13:00:00 - Sell for 1595.3296361502635$ of BTC at 8095.0$
2018-04-09 00:00:00 - Buy for 1595.3296361502635$ of BTC at price : 7060.0$
2018-04-10 00:00:00 - Sell for 1528.8071019312442$ of BTC at 6765.61$
2018-04-12 10:00:00 - Buy for 1528.8071019312442$ of BTC at price : 6935.1$
2018-05-01 19:00:00 - Sell for 1979.4889688589417$ of BTC at 8979.52$
2018-05-03 16:00:00 - Buy for 1979.4889688589417$ of BTC at price : 9613.12$
2018-05-08 11:00:00 - Sell for 1894.0093887899604$ of BTC at 9198.0$
2018-05-21 12:00:00 - Buy for 1894.0093887899604$ of BTC at price : 8493.71$
2018-05-23 01:00:00 - Sell for 1763.2861684315615$ of BTC at 7907.48$
2018-05-31 11:00:00 - Buy for 1763.2861684315615$ of BTC at price : 7531.97$
2018-06-06 14:00:00 - Sell for 1784.704608965685$ of BTC at 7623.46$
2018-06-06 15:00:00 - Buy for 1784.704608965685$ of BTC at price : 7650.5$
2018-06-06 16:00:00 - Sell for 1753.5594665118574$ of BTC at 7516.99$
2018-06-06 21:00:00 - Buy for 1753.5594665118574$ of BTC at price : 7664.99$
2018-06-10 02:00:00 - Sell for 1674.8791066258357$ of BTC at 7321.07$
2018-06-19 12:00:00 - Buy for 1674.8791066258357$ of BTC at price : 6765.82$
2018-06-22 22:00:00 - Sell for 1502.893706581451$ of BTC at 6071.07$
2018-06-30 23:00:00 - Buy for 1502.893706581451$ of BTC at price : 6390.07$
2018-07-10 23:00:00 - Sell for 1480.983214567259$ of BTC at 6296.91$
2018-07-16 21:00:00 - Buy for 1480.983214567259$ of BTC at price : 6665.6$
2018-07-31 16:00:00 - Sell for 1734.8962047616315$ of BTC at 7808.41$
2018-08-16 16:00:00 - Buy for 1734.8962047616315$ of BTC at price : 6391.51$
2018-09-06 07:00:00 - Sell for 1738.7967632309799$ of BTC at 6405.88$
2018-09-14 03:00:00 - Buy for 1738.7967632309799$ of BTC at price : 6542.37$
2018-09-18 10:00:00 - Sell for 1661.0735948013028$ of BTC at 6249.93$
2018-09-21 11:00:00 - Buy for 1661.0735948013028$ of BTC at price : 6742.23$
2018-09-26 03:00:00 - Sell for 1574.418376053283$ of BTC at 6390.5$
2018-09-28 22:00:00 - Buy for 1574.418376053283$ of BTC at price : 6633.81$
2018-10-03 14:00:00 - Sell for 1550.0300935545024$ of BTC at 6531.05$
2018-10-06 00:00:00 - Buy for 1550.0300935545024$ of BTC at price : 6624.47$
2018-10-11 07:00:00 - Sell for 1474.3100376745342$ of BTC at 6300.86$
2018-10-15 16:00:00 - Buy for 1474.3100376745342$ of BTC at price : 6927.49$
2018-10-20 22:00:00 - Sell for 1402.4874653554978$ of BTC at 6590.01$
2018-11-04 23:00:00 - Buy for 1402.4874653554978$ of BTC at price : 6485.85$
2018-11-10 12:00:00 - Sell for 1395.9224785845743$ of BTC at 6455.49$
2018-11-30 00:00:00 - Buy for 1395.9224785845743$ of BTC at price : 4242.99$
2018-12-04 02:00:00 - Sell for 1279.997801751949$ of BTC at 3890.63$
2018-12-18 10:00:00 - Buy for 1279.997801751949$ of BTC at price : 3474.0$
2018-12-26 10:00:00 - Sell for 1371.0567127263234$ of BTC at 3721.14$
2019-01-02 19:00:00 - Buy for 1371.0567127263234$ of BTC at price : 3824.98$
2019-01-11 01:00:00 - Sell for 1287.8860061987366$ of BTC at 3592.95$
2019-01-18 12:00:00 - Buy for 1287.8860061987366$ of BTC at price : 3589.3$
2019-01-21 19:00:00 - Sell for 1266.1850211445758$ of BTC at 3528.82$
2019-01-27 20:00:00 - Buy for 1266.1850211445758$ of BTC at price : 3568.68$
2019-01-28 05:00:00 - Sell for 1219.8971786205834$ of BTC at 3438.22$
2019-02-03 19:00:00 - Buy for 1219.8971786205834$ of BTC at price : 3445.6$
2019-02-06 15:00:00 - Sell for 1211.5487993914583$ of BTC at 3422.02$
2019-02-09 00:00:00 - Buy for 1211.5487993914583$ of BTC at price : 3654.84$
2019-02-16 02:00:00 - Sell for 1197.7587483756313$ of BTC at 3613.24$
2019-02-17 22:00:00 - Buy for 1197.7587483756313$ of BTC at price : 3641.27$
2019-02-26 00:00:00 - Sell for 1259.8954829677261$ of BTC at 3830.17$
2019-03-06 22:00:00 - Buy for 1259.8954829677261$ of BTC at price : 3865.41$
2019-03-13 15:00:00 - Sell for 1262.043433956821$ of BTC at 3872.0$
2019-03-16 01:00:00 - Buy for 1262.043433956821$ of BTC at price : 3960.01$
2019-03-23 14:00:00 - Sell for 1271.6011579485191$ of BTC at 3990.0$
2019-03-28 12:00:00 - Buy for 1271.6011579485191$ of BTC at price : 4016.56$
2019-04-12 18:00:00 - Sell for 1593.4556516459124$ of BTC at 5033.19$
2019-04-17 08:00:00 - Buy for 1593.4556516459124$ of BTC at price : 5169.67$
2019-04-27 09:00:00 - Sell for 1627.1546123908822$ of BTC at 5279.0$
2019-05-02 07:00:00 - Buy for 1627.1546123908822$ of BTC at price : 5406.31$
2019-05-18 20:00:00 - Sell for 2194.293528557132$ of BTC at 7290.66$
2019-05-19 18:00:00 - Buy for 2194.293528557132$ of BTC at price : 7974.23$
2019-06-01 21:00:00 - Sell for 2362.1353562625563$ of BTC at 8584.18$
2019-06-01 23:00:00 - Buy for 2362.1353562625563$ of BTC at price : 8544.07$
2019-06-04 00:00:00 - Sell for 2208.437466385647$ of BTC at 7988.13$
2019-06-12 03:00:00 - Buy for 2208.437466385647$ of BTC at price : 7959.76$
2019-07-01 08:00:00 - Sell for 3101.3611810225525$ of BTC at 11178.08$
2019-07-05 00:00:00 - Buy for 3101.3611810225525$ of BTC at price : 11170.81$
2019-07-06 13:00:00 - Sell for 3147.5006476032336$ of BTC at 11337.0$
2019-07-07 08:00:00 - Buy for 3147.5006476032336$ of BTC at price : 11185.4$
2019-07-12 14:00:00 - Sell for 3259.557230996636$ of BTC at 11583.62$
2019-07-20 19:00:00 - Buy for 3259.557230996636$ of BTC at price : 10898.66$
2019-07-23 22:00:00 - Sell for 3000.0705560515235$ of BTC at 10031.04$
2019-08-01 03:00:00 - Buy for 3000.0705560515235$ of BTC at price : 9988.02$
2019-08-11 20:00:00 - Sell for 3434.695445989212$ of BTC at 11435.0$
2019-08-20 15:00:00 - Buy for 3434.695445989212$ of BTC at price : 10744.54$
2019-08-22 04:00:00 - Sell for 3188.492840890067$ of BTC at 9974.36$
2019-09-03 06:00:00 - Buy for 3188.492840890067$ of BTC at price : 10375.67$
2019-09-09 22:00:00 - Sell for 3175.475411004565$ of BTC at 10333.31$
2019-09-14 15:00:00 - Buy for 3175.475411004565$ of BTC at price : 10356.32$
2019-09-17 15:00:00 - Sell for 3127.72823527017$ of BTC at 10200.6$
2019-10-02 14:00:00 - Buy for 3127.72823527017$ of BTC at price : 8236.44$
2019-10-05 07:00:00 - Sell for 3078.954078651764$ of BTC at 8108.0$
2019-10-09 07:00:00 - Buy for 3078.954078651764$ of BTC at price : 8179.6$
2019-10-15 13:00:00 - Sell for 3123.9586937482973$ of BTC at 8299.16$
2019-10-22 00:00:00 - Buy for 3123.9586937482973$ of BTC at price : 8185.3$
2019-10-23 18:00:00 - Sell for 2864.8456451905663$ of BTC at 7506.38$
2019-10-26 07:00:00 - Buy for 2864.8456451905663$ of BTC at price : 9481.47$
2019-11-02 15:00:00 - Sell for 2817.3745358250476$ of BTC at 9324.36$
2019-11-05 13:00:00 - Buy for 2817.3745358250476$ of BTC at price : 9237.82$
2019-11-08 13:00:00 - Sell for 2687.076811584855$ of BTC at 8810.59$
2019-11-28 21:00:00 - Buy for 2687.076811584855$ of BTC at price : 7548.39$
2019-12-02 23:00:00 - Sell for 2596.6187021612786$ of BTC at 7294.28$
2019-12-07 07:00:00 - Buy for 2596.6187021612786$ of BTC at price : 7521.48$
2019-12-11 00:00:00 - Sell for 2499.2335904953998$ of BTC at 7239.39$
2019-12-20 10:00:00 - Buy for 2499.2335904953998$ of BTC at price : 7144.94$
2019-12-26 21:00:00 - Sell for 2518.4545896637237$ of BTC at 7199.89$
2019-12-29 03:00:00 - Buy for 2518.4545896637237$ of BTC at price : 7307.27$
2019-12-31 22:00:00 - Sell for 2481.6493579383064$ of BTC at 7200.48$
2020-01-04 22:00:00 - Buy for 2481.6493579383064$ of BTC at price : 7350.24$
2020-01-21 09:00:00 - Sell for 2913.803509187829$ of BTC at 8630.21$
2020-01-27 19:00:00 - Buy for 2913.803509187829$ of BTC at price : 8932.12$
2020-02-04 22:00:00 - Sell for 3001.9993593044887$ of BTC at 9202.48$
2020-02-06 06:00:00 - Buy for 3001.9993593044887$ of BTC at price : 9649.07$
2020-02-16 17:00:00 - Sell for 3034.9654225739964$ of BTC at 9755.03$
2020-02-24 11:00:00 - Buy for 3034.9654225739964$ of BTC at price : 9811.38$
2020-02-25 09:00:00 - Sell for 2957.6264493661556$ of BTC at 9561.36$
2020-03-05 02:00:00 - Buy for 2957.6264493661556$ of BTC at price : 8919.89$
2020-03-08 23:00:00 - Sell for 2663.6573020471815$ of BTC at 8033.31$
2020-03-20 02:00:00 - Buy for 2663.6573020471815$ of BTC at price : 6150.04$
2020-03-29 05:00:00 - Sell for 2662.2150384495762$ of BTC at 6146.71$
2020-04-02 12:00:00 - Buy for 2662.2150384495762$ of BTC at price : 6656.76$
2020-04-11 12:00:00 - Sell for 2749.3190403024773$ of BTC at 6874.56$
2020-04-17 15:00:00 - Buy for 2749.3190403024773$ of BTC at price : 7037.94$
2020-04-21 21:00:00 - Sell for 2690.7460918398656$ of BTC at 6888.0$
2020-04-23 14:00:00 - Buy for 2690.7460918398656$ of BTC at price : 7536.36$
2020-05-11 01:00:00 - Sell for 3110.994419600232$ of BTC at 8713.41$
2020-05-14 20:00:00 - Buy for 3110.994419600232$ of BTC at price : 9655.88$
2020-05-21 18:00:00 - Sell for 2845.312967646527$ of BTC at 8831.26$
2020-05-28 20:00:00 - Buy for 2845.312967646527$ of BTC at price : 9450.18$
2020-06-07 14:00:00 - Sell for 2846.5925813800745$ of BTC at 9454.43$
2020-06-08 20:00:00 - Buy for 2846.5925813800745$ of BTC at price : 9701.69$
2020-06-08 22:00:00 - Sell for 2844.6296548827904$ of BTC at 9695.0$
2020-06-08 23:00:00 - Buy for 2844.6296548827904$ of BTC at price : 9782.01$
2020-06-09 01:00:00 - Sell for 2820.3389503064955$ of BTC at 9698.48$
2020-06-09 14:00:00 - Buy for 2820.3389503064955$ of BTC at price : 9713.76$
2020-06-12 02:00:00 - Sell for 2717.185277345161$ of BTC at 9358.48$
2020-06-22 17:00:00 - Buy for 2717.185277345161$ of BTC at price : 9587.21$
2020-06-25 16:00:00 - Sell for 2632.803317147776$ of BTC at 9289.48$
2020-07-02 13:00:00 - Buy for 2632.803317147776$ of BTC at price : 9246.92$
2020-07-03 18:00:00 - Sell for 2585.0667946999774$ of BTC at 9079.26$
2020-07-06 23:00:00 - Buy for 2585.0667946999774$ of BTC at price : 9344.2$
2020-07-14 04:00:00 - Sell for 2542.3991664657165$ of BTC at 9189.97$
2020-07-21 12:00:00 - Buy for 2542.3991664657165$ of BTC at price : 9367.57$
2020-08-12 14:00:00 - Sell for 3144.034740287196$ of BTC at 11584.32$
2020-08-15 04:00:00 - Buy for 3144.034740287196$ of BTC at price : 11863.65$
2020-08-20 15:00:00 - Sell for 3141.5701089903637$ of BTC at 11854.35$
2020-08-30 13:00:00 - Buy for 3141.5701089903637$ of BTC at price : 11628.01$
2020-09-03 15:00:00 - Sell for 2882.8176706554$ of BTC at 10670.28$
2020-09-11 14:00:00 - Buy for 2882.8176706554$ of BTC at price : 10289.46$
2020-09-21 23:00:00 - Sell for 2918.612433996035$ of BTC at 10417.22$
2020-09-26 17:00:00 - Buy for 2918.612433996035$ of BTC at price : 10742.68$
2020-10-02 10:00:00 - Sell for 2842.122568835084$ of BTC at 10461.14$
2020-10-06 09:00:00 - Buy for 2842.122568835084$ of BTC at price : 10746.15$
2020-10-08 04:00:00 - Sell for 2812.027592763864$ of BTC at 10632.36$
2020-10-08 19:00:00 - Buy for 2812.027592763864$ of BTC at price : 10878.83$
2020-10-17 20:00:00 - Sell for 2933.552301989213$ of BTC at 11348.97$
2020-10-19 08:00:00 - Buy for 2933.552301989213$ of BTC at price : 11466.39$
2020-11-26 20:00:00 - Sell for 4384.1453429673$ of BTC at 17136.33$
2020-11-30 14:00:00 - Buy for 4384.1453429673$ of BTC at price : 19480.8$
2020-12-08 17:00:00 - Sell for 4259.605170523423$ of BTC at 18927.41$
2020-12-13 20:00:00 - Buy for 4259.605170523423$ of BTC at price : 19154.57$
2021-01-12 07:00:00 - Sell for 8097.678978821854$ of BTC at 36413.6$
2021-01-15 10:00:00 - Buy for 8097.678978821854$ of BTC at price : 38441.89$
2021-01-16 23:00:00 - Sell for 7582.244080327817$ of BTC at 35994.98$
2021-01-19 11:00:00 - Buy for 7582.244080327817$ of BTC at price : 37266.49$
2021-01-20 11:00:00 - Sell for 7004.352266362061$ of BTC at 34426.17$
2021-01-29 13:00:00 - Buy for 7004.352266362061$ of BTC at price : 38250.03$
2021-02-23 20:00:00 - Sell for 8755.799706300068$ of BTC at 47814.5$
2021-03-03 01:00:00 - Buy for 8755.799706300068$ of BTC at price : 48848.63$
2021-03-16 22:00:00 - Sell for 10081.269584741853$ of BTC at 56243.43$
2021-03-19 07:00:00 - Buy for 10081.269584741853$ of BTC at price : 57834.04$
2021-03-22 16:00:00 - Sell for 9892.93401437294$ of BTC at 56753.6$
2021-03-28 17:00:00 - Buy for 9892.93401437294$ of BTC at price : 55967.73$
2021-04-05 07:00:00 - Sell for 10119.589847986525$ of BTC at 57250.0$
2021-04-10 08:00:00 - Buy for 10119.589847986525$ of BTC at price : 60534.89$
2021-04-18 02:00:00 - Sell for 9830.272864704431$ of BTC at 58804.21$
2021-04-27 18:00:00 - Buy for 9830.272864704431$ of BTC at price : 54960.01$
2021-05-05 13:00:00 - Sell for 10060.497240946956$ of BTC at 56247.17$
2021-05-06 18:00:00 - Buy for 10060.497240946956$ of BTC at price : 55753.57$
2021-05-11 19:00:00 - Sell for 10214.845160281786$ of BTC at 56608.94$
2021-05-26 15:00:00 - Buy for 10214.845160281786$ of BTC at price : 38758.61$
2021-05-28 22:00:00 - Sell for 9240.510065092476$ of BTC at 35061.65$
2021-06-03 00:00:00 - Buy for 9240.510065092476$ of BTC at price : 37469.31$
2021-06-06 06:00:00 - Sell for 8841.95486575211$ of BTC at 35853.21$
2021-06-11 04:00:00 - Buy for 8841.95486575211$ of BTC at price : 37044.01$
2021-06-18 21:00:00 - Sell for 8509.224011752814$ of BTC at 35650.01$
2021-06-28 15:00:00 - Buy for 8509.224011752814$ of BTC at price : 34969.99$
2021-07-02 13:00:00 - Sell for 8146.668186228374$ of BTC at 33480.01$
2021-07-03 21:00:00 - Buy for 8146.668186228374$ of BTC at price : 34544.88$
2021-07-06 15:00:00 - Sell for 8028.176142539977$ of BTC at 34042.43$
2021-07-22 21:00:00 - Buy for 8028.176142539977$ of BTC at price : 32115.59$
2021-08-03 13:00:00 - Sell for 9616.533423527155$ of BTC at 38469.59$
2021-08-06 16:00:00 - Buy for 9616.533423527155$ of BTC at price : 42519.92$
2021-08-18 07:00:00 - Sell for 10166.431903250634$ of BTC at 44951.32$
2021-08-20 20:00:00 - Buy for 10166.431903250634$ of BTC at price : 48640.98$
2021-08-26 16:00:00 - Sell for 9802.07382330116$ of BTC at 46897.72$
2021-08-29 11:00:00 - Buy for 9802.07382330116$ of BTC at price : 48159.98$
2021-08-30 13:00:00 - Sell for 9723.742683387154$ of BTC at 47775.12$
2021-09-02 12:00:00 - Buy for 9723.742683387154$ of BTC at price : 50010.0$
2021-09-08 12:00:00 - Sell for 8993.489802300744$ of BTC at 46254.25$
2021-09-15 14:00:00 - Buy for 8993.489802300744$ of BTC at price : 47860.32$
2021-09-20 17:00:00 - Sell for 8276.383109668099$ of BTC at 44044.12$
2021-09-28 09:00:00 - Buy for 8276.383109668099$ of BTC at price : 41891.99$
2021-09-28 15:00:00 - Sell for 8188.5043058439915$ of BTC at 41447.18$
2021-10-01 09:00:00 - Buy for 8188.5043058439915$ of BTC at price : 44906.0$
2021-10-23 11:00:00 - Sell for 11223.905500140287$ of BTC at 61552.23$
2021-10-30 07:00:00 - Buy for 11223.905500140287$ of BTC at price : 61597.19$
2021-11-01 18:00:00 - Sell for 11034.005119390187$ of BTC at 60555.01$
2021-11-02 13:00:00 - Buy for 11034.005119390187$ of BTC at price : 63393.54$
2021-11-05 22:00:00 - Sell for 10627.440662222703$ of BTC at 61057.71$
2021-11-08 03:00:00 - Buy for 10627.440662222703$ of BTC at price : 65199.99$
2021-11-13 13:00:00 - Sell for 10365.801834858159$ of BTC at 63594.82$
2021-11-30 08:00:00 - Buy for 10365.801834858159$ of BTC at price : 56762.0$
2021-12-03 23:00:00 - Sell for 9788.55330045319$ of BTC at 53601.05$
2021-12-22 00:00:00 - Buy for 9788.55330045319$ of BTC at price : 48644.13$
2021-12-29 04:00:00 - Sell for 9614.666285441912$ of BTC at 47780.0$
2022-01-13 03:00:00 - Buy for 9614.666285441912$ of BTC at price : 43509.93$
2022-01-18 05:00:00 - Sell for 9302.4973904766$ of BTC at 42097.25$
2022-01-29 00:00:00 - Buy for 9302.4973904766$ of BTC at price : 37788.27$
2022-02-03 22:00:00 - Sell for 9091.991364570402$ of BTC at 36933.16$
2022-02-05 00:00:00 - Buy for 9091.991364570402$ of BTC at price : 41471.41$
2022-02-12 21:00:00 - Sell for 9181.090727492352$ of BTC at 41877.82$
2022-02-16 06:00:00 - Buy for 9181.090727492352$ of BTC at price : 44028.14$
2022-02-18 03:00:00 - Sell for 8485.408655948315$ of BTC at 40691.98$
2022-02-26 14:00:00 - Buy for 8485.408655948315$ of BTC at price : 39209.63$
2022-03-05 12:00:00 - Sell for 8455.093755131214$ of BTC at 39069.55$
2022-03-10 14:00:00 - Buy for 8455.093755131214$ of BTC at price : 39283.39$
2022-03-11 18:00:00 - Sell for 8316.076717510436$ of BTC at 38637.5$
2022-03-16 19:00:00 - Buy for 8316.076717510436$ of BTC at price : 40880.17$
2022-04-02 09:00:00 - Sell for 9496.41969114074$ of BTC at 46682.5$
2022-04-03 14:00:00 - Buy for 9496.41969114074$ of BTC at price : 46633.75$
2022-04-03 19:00:00 - Sell for 9449.939238796615$ of BTC at 46405.5$
2022-04-19 23:00:00 - Buy for 9449.939238796615$ of BTC at price : 41493.18$
2022-04-23 08:00:00 - Sell for 9027.705769316584$ of BTC at 39639.22$
2022-05-05 09:00:00 - Buy for 9027.705769316584$ of BTC at price : 39485.25$
2022-05-05 17:00:00 - Sell for 8417.55012614559$ of BTC at 36816.56$
2022-05-17 16:00:00 - Buy for 8417.55012614559$ of BTC at price : 30145.93$
2022-05-19 05:00:00 - Sell for 8114.326626854425$ of BTC at 29059.99$
2022-05-23 13:00:00 - Buy for 8114.326626854425$ of BTC at price : 30323.07$
2022-05-24 21:00:00 - Sell for 7917.293152386992$ of BTC at 29586.76$
2022-05-30 15:00:00 - Buy for 7917.293152386992$ of BTC at price : 30634.08$
2022-06-03 20:00:00 - Sell for 7666.172900317505$ of BTC at 29662.43$
2022-06-06 21:00:00 - Buy for 7666.172900317505$ of BTC at price : 31488.86$
2022-06-07 08:00:00 - Sell for 7219.162114208609$ of BTC at 29652.76$
2022-06-07 10:00:00 - Buy for 7219.162114208609$ of BTC at price : 29597.79$
2022-06-08 19:00:00 - Sell for 7351.44606421437$ of BTC at 30140.14$
2022-06-09 07:00:00 - Buy for 7351.44606421437$ of BTC at price : 30487.54$
2022-06-10 13:00:00 - Sell for 7088.253186760499$ of BTC at 29396.04$
2022-06-22 06:00:00 - Buy for 7088.253186760499$ of BTC at price : 20112.97$
2022-06-28 23:00:00 - Sell for 7147.572858414936$ of BTC at 20281.29$
2022-07-05 23:00:00 - Buy for 7147.572858414936$ of BTC at price : 20175.83$

In [67]:
import ta

In [69]:

# Code to calculate RSI using the ta library from documentation

# ta.momentum.RSIIndicator(close: pandas.core.series.Series, window: int = 14, fillna: bool = False)

In [71]:
df['RSI'] = ta.momentum.RSIIndicator(df['close'], window = 14).rsi()
df

,open,high,low,close,volume,ma50,ma200,buy_signal,sell_signal,RSI
date,,,,,,,,,,
2017-08-17 04:00:00+00:00,4261.48,4313.62,4261.32,4308.83,47.181009,NaN,NaN,False,False,NaN
2017-08-17 05:00:00+00:00,4308.83,4328.69,4291.37,4315.32,23.234916,NaN,NaN,False,False,NaN
2017-08-17 06:00:00+00:00,4330.29,4345.45,4309.37,4324.35,7.229691,NaN,NaN,False,False,NaN
2017-08-17 07:00:00+00:00,4316.62,4349.99,4287.41,4349.99,4.443249,NaN,NaN,False,False,NaN
2017-08-17 08:00:00+00:00,4333.32,4377.85,4333.32,4360.69,0.972807,NaN,NaN,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...
2023-07-03 06:00:00+00:00,30673.61,30678.41,30606.00,30651.25,1036.522350,30558.3664,30477.55635,True,False,54.549107
2023-07-03 07:00:00+00:00,30651.25,30759.80,30636.65,30667.19,1758.796390,30563.1230,30478.25515,True,False,55.885094
2023-07-03 08:00:00+00:00,30667.19,30700.92,30599.07,30640.12,1390.909010,30566.9202,30478.88960,True,False,53.034081
2023-07-03 09:00:00+00:00,30640.11,30670.00,30602.29,30610.61,833.620010,30569.9348,30478.95005,True,False,50.037249
2023-07-03 10:00:00+00:00,30610.60,30623.08,30605.66,30615.85,91.875210,30573.4178,30478.92280,True,False,50.571362